# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set <key> <value>
description: Update configuration with a value for the given key
flags:
    -h, --host=: Set per-host setting
documentation:
    command: '[AI] `gh config set` is a GitHub CLI (Command Line Interface) command used to configure global settings for GitHub actions and other functionalities. The command sets a new configuration variable with the given key and value. For example, `gh config set github_token <your_token>` sets the global GitHub token.'
    flag:
        host: '[AI] The `gh config set --host` command is used with GitHub''s `git-hub` CLI (Command Line Interface) tool to configure a new or update an existing GitHub host configuration. This particular command sets the value for the "host" key in the configuration file, typically located at `~/.config/gh/config`. It can be used to specify the URL of a custom GitHub Enterprise server instead of the default public GitHub platform. The format is `gh config set --host <github_url>`, where `<github_url>` is the URL of the GitHub instance you want to configure.'
