# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: clear-cache
description: Clear the cli cache
documentation:
    command: '[AI] `gh config clear-cache` is a GitHub CLI (Command Line Interface) command used to clear the local configuration cache. This action can be helpful when experiencing issues with outdated or incorrect configuration settings, ensuring that all future GitHub CLI interactions will use the most current and accurate configurations directly from the remote server.'
