# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
aliases:
    - ls
description: Print a list of configuration keys and values
flags:
    -h, --host=: Get per-host configuration
documentation:
    command: '[AI] `gh config list` is a GitHub CLI (Command Line Interface) command used to display a list of current configuration settings for GitHub actions, SSH keys, personal access tokens, and other GitHub-related configurations. It helps users understand and manage their GitHub environment settings easily.'
    flag:
        host: '[AI] The `gh config list --host` command is used in GitHub''s `git-hub` CLI tool to display a list of configurations related to the GitHub host or authentication. This command allows users to check their current GitHub configurations such as the base URL, token, and SSH key path for authenticating with GitHub. It does not modify any settings but only shows the existing ones.'
