# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get <key>
description: Print the value of a given configuration key
flags:
    -h, --host=: Get per-host setting
documentation:
    command: '[AI] `gh config get` is a GitHub CLI (Command Line Interface) command used to retrieve the value of a specific configuration setting from your GitHub global or user-specific configuration file. For instance, if you want to check the current personal access token, you can use: `gh config get token.access_token`.'
    flag:
        host: '[AI] The `gh config get --host` command is used with GitHub''s `gh` CLI (Command Line Interface) tool. This command retrieves the value configured for the ''host'' key in the user''s GitHub configuration file. The configuration file, located at `~/.config/gh/config.yml`, stores various settings related to GitHub interactions such as personal access tokens, default branch names, and more. By executing `gh config get --host`, you can obtain the URL for interacting with GitHub''s API or other services, based on your currently configured setting.'
