# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config <command>
description: Manage configuration for gh
documentation:
    command: '[AI] `gh config` is a GitHub CLI (Command Line Interface) command used to configure global settings for GitHub actions and other GitHub-related tools. It allows users to set various preferences such as personal access tokens, default branch, and editor. The command accepts different subcommands like `config get`, `config set`, or `config rm` to retrieve, modify, or remove specific configurations respectively.'
