# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: environment
description: Environment variables that can be used with gh
hidden: true
documentation:
    command: '[AI] `gh environment` is a GitHub CLI (Command Line Interface) command used to manage and display encrypted GitHub Secrets as environment variables locally. It allows users to add, remove, or list encrypted secrets from their GitHub account. The output is displayed in the terminal with the secret name and value hidden for security reasons.'
