# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: show-environment
flags:
    -g: TODO description
    -h: TODO description
    -s: TODO description
    -t=: target-session
documentation:
    command: '[AI] `tmux show-environment` is a TMUX command used to display all the current variables and their values within the current terminal multiplexer session. It helps in understanding the environment settings specific to that session, which can be useful for debugging or configuring applications running inside it.'
    flag:
        g: '[AI] `tmux show-environment -g` is a command in the TMUX terminal multiplexer that displays all the current session and window environment variables as key-value pairs, with the `-g` option making it print them globally across all sessions and panes. It''s useful for quickly checking or setting environment variables within a TMUX session.'
        h: |-
            [AI] `tmux show-environment` is a command used in the Tmux terminal multiplexer to display the current environment variables in the specified pane or session. The `-h` option stands for "display as a horizontal list", meaning that the output will be displayed as a single line with each variable name followed by its value, separated by an equal sign and space. For instance:

            ```sh
            VAR1=value1 VAR2=value2 ...
            ```
        s: '[AI] `tmux show-environment` is a command used in the TMUX terminal multiplexer to display all or specific environment variables for the current session or named sessions. The `-s` option allows specifying a named session to query. For instance, `tmux show-environment -s mysession` will display the environment variables of the session named "mysession".'
        t: '[AI] `tmux show-environment -t` is a TMUX command used to display all variables in the current terminal pane or window''s environment. The ''-t'' option specifies that only the terminal names or identifiers are printed before the environment variables, for easier identification of which environment the variables belong to.'
