# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Config
documentation:
    command: '[AI] `golangci-lint config` is a command used with the Golang static analyzer tool, golangci-lint. It reads and displays the current configuration settings of the tool. These settings include enabled rules, custom messages, and other options that control the behavior of golangci-lint when running on Go codebase. This information can be useful for understanding and managing the linting process in a project.'
