# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Operate on build config files
documentation:
    command: '[AI] `circleci config` is a command used in CircleCI, a continuous integration and delivery platform. It is used to configure CircleCI''s YAML configuration files, which define the workflows and jobs for building, testing, and deploying projects. The command allows users to edit their existing configuration files or create new ones interactively in the CircleCI web interface. Changes can be saved and applied to the project''s build processes upon confirmation.'
