# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: unset
description: Unset the value associated with name
documentation:
    command: '[AI] `pip config unset` is a command used in Python''s package installer, pip, to remove or unset a specific configuration option. When you run this command followed by the name of the configuration variable you want to unset (without the "config" keyword), pip will delete that particular setting from your pip.conf file. This command is particularly useful when you want to temporarily disable or reset a pip configuration.'
