# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set
description: Set the value
documentation:
    command: '[AI] `pip config set` is a command used with pip, which is a package manager for Python. This command allows you to configure pip''s settings by setting or modifying key-value pairs in the pip configuration file (located at ~/.pip/pip.conf by default). The general syntax is: `pip config set <option> <value>`. For example, `pip config set global.index-url "http://my.repo.com/simple"` sets the global index URL to the given address.'
