# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get
description: Get the value associated with name
documentation:
    command: '[AI] `pip config get` is a pip (Python Package Installer) command used to retrieve the value of a specific configuration option set up in your pip configuration file. For instance, `pip config get global.index-url` will output the URL for the Python package index. This command helps in querying and managing various configurations used by pip.'
