# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
description: List the active configuration
documentation:
    command: '[AI] `pip config list` is a command used in Python programming language to display the current configuration settings for pip, which is the package installer for Python. The output shows key-value pairs that define global options for pip, such as the index URLs from where packages are installed by default and the location of the cache and logs directories.'
