# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: edit
description: Edit the configuration file in an editor
flags:
    --editor=: Editor to use to edit the file
documentation:
    command: '[AI] `pip config edit` is a command used with pip, the Python package installer. It opens the pip configuration file in a text editor, allowing you to edit its contents directly. This can be useful for changing global settings such as the default download location or index URLs for packages. After editing, save the changes and pip will apply them during installation processes.'
    flag:
        editor: '[AI] `pip config edit` is a command used with pip, the Python package installer. This command opens the site-wide pip configuration file in your default text editor so that you can edit it directly. The `--editor` option specifies which text editor to use for this operation. For example, `pip config edit --editor=nano` will open the configuration file in the nano text editor on Unix-based systems. The changes made to the configuration file while it''s open in the editor will be saved when you save and close the file.'
