# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Inspect configuration values
flags:
    -h, --help: Print help
documentation:
    command: '[AI] `cargo config` is a Cargo subcommand used to manage project-level configurations in Rust projects. It allows users to set key-value pair options in their `Cargo.toml` file, either by modifying existing ones or adding new ones. These configurations can include various settings like registry addresses, Git repository URLs, and build flags, among others. The changes made with `cargo config` are persisted and will apply to subsequent Cargo builds.'
    flag:
        help: '[AI] `cargo config --help` is a command used with Cargo, Rust''s package manager. This command displays detailed help information about the `config` sub-command. The `config` sub-command allows users to configure various aspects of their Cargo project, such as workspace layout or repository settings. The help output includes options and their descriptions, usage examples, and contact information for support.'
