# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Edit the glow config file
documentation:
    command: '[AI] `glow config` is a command used in Glow, a machine learning framework for building deep neural networks, to load or modify the configuration settings of a specific experiment or model. These settings define various aspects such as network architecture, training data, optimization algorithms, and hyperparameters. By editing or reloading the configuration file, users can adjust the model behavior to suit their specific use case.'
