# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
description: list verbs
documentation:
    command: '[AI] `winetricks` is a graphical utility for managing WINEprefixes and installing additional components in WINE, a compatibility layer that allows running Windows applications on Linux or macOS. The command `winetricks settings list` displays the current settings of the last-used or specified WINEprefix, showing details about installed DLLs, fonts, and other components. It provides an overview of the configuration for effective application compatibility.'
