# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get-config-value
description: Get configuration value
flags:
    --as-json: Outputs the result as a JSON value
    -g, --global*=: 'set/override globals. eg.: --global name=<expr>'
documentation:
    command: |-
        [AI] `terramate experimental get-config-value` is a command used in Terraform, an open-source infrastructure as code software tool. This specific command is part of Terraform's experimental features and is used to retrieve the value of a configuration variable. The syntax is as follows:

        ```bash
        terramate experimental get-config-value <name>
        ```

        Replace `<name>` with the name of the configuration variable you wish to retrieve. This command can be helpful during development and troubleshooting, as it allows you to inspect the value of a configurable parameter without having to modify your Terraform code directly. However, keep in mind that this command is experimental and may not be supported in future versions or have certain limitations. Always ensure that you are using the most up-to-date documentation for the latest features and functionality.
    flag:
        as-json: |-
            [AI] The `terraform get-config-value` command is a part of Terraform's CLI (Command Line Interface). It is used to retrieve the value of a configuration variable or input from a Terraform configuration file or workspaces, without affecting the current state.

            The `--as-json` option is used with this command to return the output in JSON format, making it easier for scripts and other automated tools to process the data. The full command `terraform experimental get-config-value --as-json` returns the value of a configuration variable or input as a JSON object containing the key-value pair.
        global: |-
            [AI] `terraform` is an open-source infrastructure as code software tool created by Hashicorp. The command `terraform get-config <argument>` is used to retrieve the value of a configuration setting.

            The specific command `terraform get-config-value --global <flag>` retrieves the global value of the specified flag. Global flags are options that apply to all the workspaces in a Terraform configuration. The `<flag>` is the name of the particular configuration option you want to query. For instance, if you want to know the location of the backend configuration file, you can use this command: `terraform get-config-value --global backend`.
