# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: view
description: Display values currently set in the minikube config file
flags:
    --format=: Go template format string for the config view output.
