# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: defaults
description: Lists all valid default values for PROPERTY_NAME
flags:
    --output=: 'Output format. Accepted values: [json]'
