# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: completion
description: generate autocompletion scripts for the specified shell
group: main
documentation:
    command: '[AI] `helm completion` is a Helm command used to enable Autocompletion for Helm in your terminal or shell. It sets up the necessary completions for commands, chart names, and values in your shell, allowing you to benefit from suggestions as you type. This can make interacting with Helm more efficient and easier. To use it, usually you would call this command with your preferred shell''s completion function: `helm completion bash` or `helm completion zsh`.'
