# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update
description: update information of available charts locally from chart repositories
documentation:
    command: '[AI] `helm repo update` is a command used in Helm, a popular package manager for Kubernetes. This command updates your local Helm repository index, ensuring that you have the latest versions of charts and repositories available for installation or upgrades. It fetches the newest metadata from the configured Helm repositories and stores it locally. This allows users to easily manage and deploy applications on a Kubernetes cluster with the latest versions.'
