# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update
description: update one or more Helm plugins
documentation:
    command: '[AI] `helm plugin update` is a Helm command used to update Helm plugins installed on your local system. Plugins extend the functionality of Helm, the Kubernetes package manager, and are installed separately from Helm itself. By running this command, you ensure that your Helm plugins are up-to-date with their latest versions. This helps maintain the stability and compatibility of your Helm setup while taking advantage of new features and bug fixes.'
