# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
description: list the dependencies for the given chart
flags:
    --max-col-width=: maximum column width for output table
documentation:
    command: '[AI] The `helm dependency list` command is used to show the dependencies of a Helm chart. It lists out the names and versions of the charts that are required to be installed before installing or upgrading the chart in question. This helps in understanding the dependencies and managing them effectively.'
    flag:
        max-col-width: '[AI] `helm dependency list --max-col-Width` is a command used in Helm, a popular Kubernetes packaging and deployment tool. This specific command generates a list of dependencies for a given Helm chart with a maximum column width to ensure the output fits within a specified limit when displayed in the terminal. It helps prevent long lines and improves readability by truncating the output if necessary.'
