# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: index
description: generate an index file given a directory containing packaged charts
flags:
    --merge=: merge the generated index into the given index
    --url=: url of chart repository
documentation:
    command: '[AI] `helm repo index` is a Helm command used to retrieve the list of charts and their versions available in a specific Helm repository. It updates your local chart repository index with the latest information from the remote chart repository. This command helps you discover and manage the available Helm charts for deployment in your Kubernetes environment.'
    flag:
        merge: |-
            [AI] `helm repo index --merge` is a command used in Helm, a popular package manager for Kubernetes applications. This command performs the following actions:

            1. It fetches the latest repository metadata from the specified Helm repositories.
            2. Merges the newly fetched metadata with the existing local index, ensuring that the local index stays up-to-date.
            3. The merged index contains all the available versions and charts for each repository, ready to be searched using `helm search`.

            By executing this command regularly, you ensure your Helm environment has access to the latest chart versions from their respective repositories.
        url: '[AI] `helm repo index --url` is a command used with Helm, a popular package manager for Kubernetes. This specific command retrieves the list of available charts and their versions from a specified Helm repository, which is identified by the URL provided after the `--url` flag. The output shows the chart name, version, and other metadata, helping users to discover and choose suitable charts for deploying applications in their Kubernetes clusters.'
