# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: history
description: fetch release history
group: main
flags:
    --max=: maximum number of revision to include in history
    -o, --output=: 'prints the output in the specified format. Allowed values: table, json, yaml'
documentation:
    command: '[AI] `helm history` is a Helm command used to display the installation history of Helm charts. It lists the releases (instances of deploying a chart) that have been installed, their status, and other relevant details such as the release version, the time of creation, and the namespace where the release was deployed. This command helps in tracking and managing the lifecycle of Helm releases.'
    flag:
        max: '[AI] `helm history --max` is a command used in Helm, the Kubernetes Package Manager, to retrieve the last `n` number of releases history records. The `--max` option sets the maximum number of records to display, making it useful for viewing a limited amount of historical data when dealing with numerous releases.'
        output: '[AI] `helm history --output` is a Helm command used to retrieve the installation history of a Helm chart. The `--output` option specifies the desired output format, which can be `json`, `table`, or `yaml`. This command returns detailed information about each installation record, including the release name, version, status, and installation time.'
