# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: repo
description: add, list, remove, update, and index chart repositories
group: main
documentation:
    command: |-
        [AI] `helm repo` is a command used with Helm, the popular Kubernetes Package Manager. It allows users to interact with Helm repositories, which are remote sources of Helm charts. Specifically, the following subcommands are available:

        1. `add <REMOTE> [<LOCAL_DIR>]`: Adds a new Helm repository to your Helm repositories list. `<REMOTE>` is the URL of the remote Helm repository, and `<LOCAL_DIR>` (optional) is the local directory where you want to store the charts from this repo.
        2. `update`: Updates all Helm repositories listed in your configuration file. This ensures that you have the latest versions of charts available from those repositories.
        3. `search <QUERY>`: Searches for Helm charts in all repositories listed in your configuration file. The search query is specified by `<QUERY>`.
        4. `inspect <REPOSITORY>/<CHART>`: Shows the details of a specific chart, including its version, description, and dependencies. This command requires specifying both the Helm repository (`<REPOSITORY>`) and the chart name (`<CHART>`).
