# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: plugin
description: install, list, or uninstall Helm plugins
group: main
documentation:
    command: '[AI] `helm plugin` is a Helm command used to manage and install plugins for Helm, which is a popular package manager for Kubernetes applications. Plugins extend Helm''s functionality by adding new features or capabilities. To use this command, you can list available plugins with `helm plugin repair`, install a specific plugin with `helm plugin install <plugin-repo> <plugin-name>`, or update an installed plugin with `helm plugin update <plugin-name>`.'
