# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: show
description: show information of a chart
group: main
documentation:
    command: '[AI] `helm show` is a command used in Helm, the Kubernetes Package Manager. This command is used to display detailed information about a specific Helm chart or release. When you run `helm show <chart-name>`, it shows the detailed description of that chart including its version, dependencies, values, and other relevant metadata. Similarly, running `helm show releases <release-name>` will display the details of a specific deployed release, including its chart, version, status, and other relevant information.'
