# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: remove
description: remove one or more chart repositories
documentation:
    command: |-
        [AI] `helm repo remove` is a Helm command used to delete a specific repository from your local Helm chart repository list. The basic usage of this command is:

        ```bash
        helm repo remove <repository-url>
        ```

        Replace `<repository-url>` with the URL of the Helm repository you want to remove. When executed, it will delete the specified repository from your local Helm cache and stop any automatic updates for charts in that repository.
