# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get
description: download extended information of a named release
group: main
documentation:
    command: '[AI] `helm get` is a command used in Helm, a popular package manager for Kubernetes applications. This command is used to retrieve files or charts from a Helm repository without installing or upgrading them. The basic syntax is `helm get <REPO_URL> <CHART_NAME> [VERSION] [FILE_PATH]`. It fetches the specified chart or file from the given repository with an optional version and saves it locally in the current working directory under the `helm-charts` folder by default. If a specific file path is provided, the command will only download that file instead of the entire chart.'
