# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: version
description: print the client version information
group: main
flags:
    --short: print the version number
    --template=: template for version string format
    -c, --client: display client version information
documentation:
    command: '[AI] The `helm version` command is used to display the version information of Helm, the popular package manager for Kubernetes. When executed, it returns the version number, Git commit hash, and build date of both Helm client and Tiller server components if installed.'
    flag:
        client: '[AI] `helm version --client` is a command used in Helm, a popular package manager for Kubernetes. This command returns the version information of the Helm client that''s currently installed and being used to execute the command. It helps users ensure they are using the latest or desired version of Helm client while managing their applications deployed on Kubernetes.'
        short: '[AI] `helm version --short` is a command used in Helm, the popular package manager for Kubernetes. The `--short` flag option requests that Helm print only the major and minor versions of its installed release, excluding any build or revision numbers. For example, if Helm is version 3.2.5, running this command would output "3.2".'
        template: '[AI] `helm version --template` is a command used in Helm, the Kubernetes Package Manager. It returns the version of Helm installed on your local system, but with the added feature of using Go templates to manipulate and output the version string in a customized way. The `--template` option allows specifying a Go template to format the output. This can be useful for integrating Helm version information into other scripts or tools.'
