# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: unset-environment
description: Unset one or more environment variables
group: environment
documentation:
    command: '[AI] `systemctl unset-environment` is a command used in Linux systems, specifically with systemd, to remove an environment variable that was previously set for system services or systemd managed processes. The command takes the name of the environment variable as its argument and removes it from the current default environment for systemctl controlled processes. This change does not affect user sessions or the overall system settings. It is useful when you want to prevent a service from using a specific environment variable at startup.'
