# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: show-environment
description: Dump environment
group: environment
documentation:
    command: '[AI] `systemctl show-environment` is a command used in Linux systems with systemd as the init system. This command displays the current values of various system and environment variables that are relevant to the systemd service manager. The output shows key-value pairs for variables such as PATH, LD_LIBRARY_PATH, and other system-specific settings that can impact systemd''s behavior. It''s a useful command when troubleshooting or configuring system services.'
