# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: import-environment
description: Import all or some environment variables
group: environment
documentation:
    command: '[AI] `systemctl import-environment` is a command in Systemd, a system and service manager for Linux operating systems. This command imports variables from a file into the system''s environment, making them available to processes and services managed by Systemd. The file containing the variables must be in key-value format, with one variable per line. For example: `systemctl import-environment /path/to/file.conf`. Once imported, these variables can be accessed using the $VARIABLE syntax.'
