# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update
description: Update disk config.
flags:
    --ids=:
        description: One or more resource IDs (space-delimited).
        nargs: -1
    --no-wait=:
        description: Do not wait for the long-running operation to finish.
        nargs: -1
    --subscription=: Name or ID of subscription.
    -g, --resource-group=: Name of resource group.
    -n, --name=: The name of the managed disk that is being created.
    -z, --size-gb=: If creationData.createOption is Empty, this field is mandatory and it indicates the size of the disk to create.
completion:
    flag:
        no-wait:
            - "true"
            - t
            - "yes"
            - "y"
            - "1"
            - "false"
            - f
            - "no"
            - "n"
            - "0"
documentation:
    flag:
        acquire-policy-token: Acquiring an Azure Policy token automatically for this resource operation.
        change-reference: The related change reference ID for this resource operation.
        ids: One or more resource IDs (space-delimited). It should be a complete resource ID containing all information of 'Resource Id' arguments. You should provide either --ids or other 'Resource Id' arguments.
        name: The name of the managed disk that is being created. The name can't be changed after the disk is created. Supported characters for the name are a-z, A-Z, 0-9, _ and -. The maximum name length is 80 characters.
        no-wait: |-
            Do not wait for the long-running operation to finish.

            Accepted values: 0, 1, f, false, n, no, t, true, y, yes
        resource-group: Name of resource group. You can configure the default group using ``` az configure --defaults group=<name> ``` .
        size-gb: If creationData.createOption is Empty, this field is mandatory and it indicates the size of the disk to create. If this field is present for updates or creation with other options, it indicates a resize. Resizes are only allowed if the disk is not attached to a running VM, and can only increase the disk's size.
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
examples:
    Update disk size.: az disk config update --name MyManagedDisk --resource-group MyResourceGroup --size-gb 20
