# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update
description: Update an application gateway WAF policy custom rule.
flags:
    --action=: Action to take.
    --add=:
        description: Add an object to a list of objects by specifying a path and key value pairs.
        nargs: -1
    --force-string=:
        description: When using 'set' or 'add', preserve string literals instead of attempting to convert to JSON.
        nargs: -1
    --group-by-user-session=:
        description: List of user session identifier group by clauses.
        nargs: -1
    --match-conditions=:
        description: List of match conditions.
        nargs: -1
    --policy-name=!: Name of the application gateway WAF policy.
    --priority=: Rule priority.
    --rate-limit-duration=: Duration over which Rate Limit policy will be applied.
    --rate-limit-threshold=: Rate Limit threshold to apply in case ruleType is RateLimitRule.
    --remove=:
        description: Remove a property or an element from a list.
        nargs: -1
    --rule-type=: Type of rule.
    --set=:
        description: Update an object by specifying a property path and value to set.
        nargs: -1
    --state=: Describe if the custom rule is in enabled or disabled state.
    --subscription=: Name or ID of subscription.
    -g, --resource-group=!: Name of resource group.
    -n, --name=!: Name of the WAF policy rule.
completion:
    flag:
        action:
            - Allow
            - Block
            - JSChallenge
            - Log
        force-string:
            - "true"
            - t
            - "yes"
            - "y"
            - "1"
            - "false"
            - f
            - "no"
            - "n"
            - "0"
        rate-limit-duration:
            - FiveMins
            - OneMin
        rule-type:
            - Invalid
            - MatchRule
            - RateLimitRule
        state:
            - Disabled
            - Enabled
documentation:
    flag:
        acquire-policy-token: Acquiring an Azure Policy token automatically for this resource operation.
        action: |-
            Action to take.

            Accepted values: Allow, Block, JSChallenge, Log
        add: 'Add an object to a list of objects by specifying a path and key value pairs.  Example: ``` --add property.listProperty <key=value, string or JSON string> ``` .'
        change-reference: The related change reference ID for this resource operation.
        force-string: |-
            When using 'set' or 'add', preserve string literals instead of attempting to convert to JSON.

            Accepted values: 0, 1, f, false, n, no, t, true, y, yes
        group-by-user-session: List of user session identifier group by clauses.  Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
        match-conditions: List of match conditions.  Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
        name: Name of the WAF policy rule.
        policy-name: Name of the application gateway WAF policy.
        priority: Rule priority. Lower values are evaluated prior to higher values.
        rate-limit-duration: |-
            Duration over which Rate Limit policy will be applied. Applies only when ruleType is RateLimitRule.

            Accepted values: FiveMins, OneMin
        rate-limit-threshold: Rate Limit threshold to apply in case ruleType is RateLimitRule. Must be greater than or equal to 1.
        remove: 'Remove a property or an element from a list.  Example: ``` --remove property.list <indexToRemove> ``` OR ``` --remove propertyToRemove ``` .'
        resource-group: Name of resource group. You can configure the default group using ``` az configure --defaults group=<name> ``` .
        rule-type: |-
            Type of rule.

            Accepted values: Invalid, MatchRule, RateLimitRule
        set: 'Update an object by specifying a property path and value to set.  Example: ``` --set property1.property2=<value> ``` .'
        state: |-
            Describe if the custom rule is in enabled or disabled state.

            Accepted values: Disabled, Enabled
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
examples:
    Update an application gateway WAF policy custom rule with user session identifier.: az network application-gateway waf-policy custom-rule create -g MyResourceGroup --policy-name MyPolicy -n MyRule --rate-limit-duration OneMin --rate-limit-threshold 10 --group-by-user-session "[{group-by-variables:[{variable-name:ClientAddr}]}]"
    Update an application gateway WAF policy custom rule.: az network application-gateway waf-policy custom-rule update --action Allow --name MyWAFPolicyRule --policy-name MyPolicy --priority 500 --resource-group MyResourceGroup --rule-type MatchRule
