# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update
description: Update a Azure Service Fabric application.
flags:
    --failure-action=: Specify the action to take if the monitored upgrade fails.
    --force-restart=:
        description: Indicates that the service host restarts even if the upgrade is a configuration-only change.
        nargs: -1
    --hc-retry-timeout=: Specify the duration, in seconds, after which Service Fabric retries the health check if the previous health check fails.
    --hc-stable-duration=: Specify the duration, in seconds, that Service Fabric waits in order to verify that the application is stable before moving to the next upgrade domain or completing the upgrade.
    --hc-wait-duration=: Specify the duration, in seconds, that Service Fabric waits before it performs the initial health check after it finishes the upgrade on the upgrade domain.
    --max-nodes=: Specify the maximum number of nodes on which to place an application.
    --max-porcent-unhealthy-apps=: Specify the maximum percentage of the application instances deployed on the nodes in the cluster that have a health state of error before the application health state for the cluster is error.
    --max-porcent-unhealthy-partitions=: Specify the maximum percent of unhelthy partitions per service allowed by the health policy for the default service type to use for the monitored upgrade.
    --max-porcent-unhealthy-replicas=: Specify the maximum percent of unhelthy replicas per service allowed by the health policy for the default service type to use for the monitored upgrade.
    --max-porcent-unhealthy-services=: Specify the maximum percent of unhelthy services allowed by the health policy for the default service type to use for the monitored upgrade.
    --min-nodes=: Specify the minimum number of nodes where Service Fabric will reserve capacity for this application, this does not mean that the application is guaranteed to have replicas on all those nodes.
    --name=!: Specify the application name.
    --parameters=:
        description: Specify the application parameters as key/value pairs.
        nargs: -1
    --service-type-health-policy-map=: 'Specify the map of the health policy to use for different service types as a hash table in the following format: {"ServiceTypeName" : "MaxPercentUnhealthyPartitionsPerService,MaxPercentUnhealthyReplicasPerPartition,MaxPercentUnhealthyServices"}.'
    --subscription=: Name or ID of subscription.
    --ud-timeout=: Specify the maximum time, in seconds, that Service Fabric takes to upgrade a single upgrade domain.
    --upgrade-replica-set-check-timeout=: Specify the maximum time, in seconds, that Service Fabric waits for a service to reconfigure into a safe state, if not already in a safe state, before Service Fabric proceeds with the upgrade.
    --upgrade-timeout=: Specify the maximum time, in seconds, that Service Fabric takes for the entire upgrade.
    --version=: Specify the application type version.
    --warning-as-error=:
        description: Indicates whether to treat a warning health event as an error event during health evaluation.
        nargs: -1
    -c, --cluster-name=!: Specify the name of the cluster, if not given it will be same as resource group name
    -g, --resource-group=!: Specify the resource group name.
completion:
    flag:
        failure-action:
            - Rollback
            - Manual
        force-restart:
            - "true"
            - "false"
        warning-as-error:
            - "true"
            - "false"
documentation:
    command: Update an Azure Service Fabric application. This allows updating the application parameters and/or upgrade the application type version which will trigger an application upgrade.
    flag:
        acquire-policy-token: Acquiring an Azure Policy token automatically for this resource operation.
        change-reference: |-
            The related change reference ID for this resource operation.

            Default value: False

            Accepted values: false, true
        cluster-name: Specify the name of the cluster, if not given it will be same as resource group name.
        failure-action: |-
            Specify the action to take if the monitored upgrade fails. The acceptable values for this parameter are Rollback or Manual.

            Accepted values: Manual, Rollback
        force-restart: |-
            Indicates that the service host restarts even if the upgrade is a configuration-only change.

            Default value: False

            Accepted values: false, true
        hc-stable-duration: Specify the duration, in seconds, that Service Fabric waits in order to verify that the application is stable before moving to the next upgrade domain or completing the upgrade. This wait duration prevents undetected changes of health right after the health check is performed.
        max-nodes: Specify the maximum number of nodes on which to place an application. The value of this parameter must be a non-negative integer. The default value is 0, which indicates the application can be placed on any number of nodes in the cluster.
        max-porcent-unhealthy-apps: Specify the maximum percentage of the application instances deployed on the nodes in the cluster that have a health state of error before the application health state for the cluster is error. Allowed values are form 0 to 100.
        max-porcent-unhealthy-partitions: Specify the maximum percent of unhelthy partitions per service allowed by the health policy for the default service type to use for the monitored upgrade. Allowed values are form 0 to 100.
        max-porcent-unhealthy-replicas: Specify the maximum percent of unhelthy replicas per service allowed by the health policy for the default service type to use for the monitored upgrade. Allowed values are form 0 to 100.
        max-porcent-unhealthy-services: Specify the maximum percent of unhelthy services allowed by the health policy for the default service type to use for the monitored upgrade. Allowed values are form 0 to 100.
        max-unhealthy-apps: Specify the maximum percentage of the application instances deployed on the nodes in the cluster that have a health state of error before the application health state for the cluster is error. Allowed values are from 0 to 100.
        max-unhealthy-parts: Specify the maximum percent of unhealthy partitions per service allowed by the health policy for the default service type to use for the monitored upgrade. Allowed values are from 0 to 100.
        max-unhealthy-reps: Specify the maximum percent of unhealthy replicas per service allowed by the health policy for the default service type to use for the monitored upgrade. Allowed values are from 0 to 100.
        max-unhealthy-servs: Specify the maximum percent of unhealthy services allowed by the health policy for the default service type to use for the monitored upgrade. Allowed values are form 0 to 100.
        min-nodes: Specify the minimum number of nodes where Service Fabric will reserve capacity for this application, this does not mean that the application is guaranteed to have replicas on all those nodes. The value of this parameter must be a non-negative integer. Default value for this is zero, which means no capacity is reserved for the application.
        parameters: 'Specify the application parameters as key/value pairs. These parameters must exist in the application manifest. for example: --application-parameters param1=value1 param2=value2'
        resource-group: Specify the resource group name. You can configure the default group using ``` az configure --defaults group=<name> ``` .
        service-type-health-policy-map: 'Specify the map of the health policy to use for different service types as a hash table in the following format: {"ServiceTypeName" : "MaxPercentUnhealthyPartitionsPerService,MaxPercentUnhealthyReplicasPerPartition,MaxPercentUnhealthyServices"}. For example: @{ "ServiceTypeName01" = "5,10,5"; "ServiceTypeName02" = "5,5,5" }. --ud-timeout --upgrade-domain-timeout Specify the maximum time, in seconds, that Service Fabric takes to upgrade a single upgrade domain. After this period, the upgrade fails.'
        subscription: Name or ID of subscription. You can configure the default subscription using `az account set -s NAME_OR_ID`
        ud-timeout: Specify the maximum time, in seconds, that Service Fabric takes to upgrade a single upgrade domain. After this period, the upgrade fails.
        upgrade-timeout: Specify the maximum time, in seconds, that Service Fabric takes for the entire upgrade. After this period, the upgrade fails.
examples:
    Update application minimum and maximum nodes.: az sf application update -g testRG -c testCluster --application-name testApp --minimum-nodes 1 --maximum-nodes 3
    Update application parameters and upgrade policy values and app type version to v2.: |-
        az sf application update -g testRG -c testCluster --application-name testApp --application-type-version v2 \
          --application-parameters key0=value0 --health-check-stable-duration 0 --health-check-wait-duration 0 --health-check-retry-timeout 0 \
            --upgrade-domain-timeout 5000 --upgrade-timeout 7000 --failure-action Rollback --replica-check-timeout 300 --force-restart
