# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: export [OPTIONS] CONTAINER
description: Export a container's filesystem as a tar archive
flags:
    -o, --output=: Write to a file, instead of STDOUT
documentation:
    command: '[AI] `docker container export` is a Docker command used to save the contents of a container''s filesystem as a tar archive. This command can be utilized when you want to save and share the contents of a container without having it running. The exported tarball can then be imported into another system using `docker load` or `docker image import`. This is often used for creating custom images based on existing containers or sharing container configurations with others.'
    flag:
        output: '[AI] The `docker container export` command is used to save the contents of a Docker container as a tar archive or a standard input stream. The `--output` option specifies where to write the output. It can be a file, a URL for a remote server, or `-` to write to standard output. This allows you to save a container''s filesystem as a portable image that can be loaded into other Docker environments.'
