# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: plugin
description: Manage plugins
group: management
documentation:
    command: |-
        [AI] The `docker plugin` command is used to manage Docker plugins, which are extensions that add new features or functionality to the Docker platform. Plugins can be thought of as containers for services, and they communicate with the Docker daemon through the Docker API.

        The specific usage of the `docker plugin` command varies depending on the task at hand. Here are some common uses:

        * `docker plugin install <plugin>`: Install a new plugin.
        * `docker plugin ls`: List installed plugins and their versions.
        * `docker plugin rm <plugin>`: Remove an installed plugin.
        * `docker plugin prune`: Remove unused plugins and their associated containers.

        These commands can be run on the Docker host machine, and they interact with the Docker daemon to manage plugins.
