# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: sign IMAGE:TAG
description: Sign an image
flags:
    --local: Sign a locally tagged image
documentation:
    command: |-
        [AI] The `docker trust` command is used to manage Docker Notary, a secure and automated registry for signing and verifying artifacts. The `docker trust sign` sub-command is responsible for creating or updating a trust key, which is a cryptographic key pair used to sign content in the registry.

        When you run `docker trust sign`, it generates a new key pair (if not already exists) and registers the public key with Docker Hub's Keybase service. This public key can be used by other clients to verify the authenticity of signed images or manifest lists, thus ensuring that the content comes from a trusted source.

        To summarize: `docker trust sign` is used to create or update a trust key in Docker Notary, which is then used for signing and verifying artifacts in a secure registry.
    flag:
        local: '[AI] `docker trust sign --local` is a command used in Docker''s Notary, a tool for managing and verifying the authenticity of Docker images. This specific command creates a new signing key on the local machine instead of using an existing one. The new private key will be stored securely on your system, while the corresponding public key gets published to the Notary server. This process allows you to sign images locally before pushing them to a registry, ensuring image integrity and authenticity.'
