# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm CONTEXT [CONTEXT...]
aliases:
    - remove
description: Remove one or more contexts
flags:
    -f, --force: Force the removal of a context in use
documentation:
    command: '[AI] The `docker context rm` command is used to remove a specified Docker context in Docker Desktop or Docker Engine. Contexts represent remote Docker registries, swarm clusters, and local environments. By providing the name or ID of the context as an argument, this command deletes the specified context from your Docker environment.'
    flag:
        force: '[AI] The `docker context rm` command is used to remove a Docker context in Docker Desktop or Docker for Windows. The `--force` option is used with this command to permanently delete the context without any confirmation prompt. After running this command, the specified context will no longer be available for use when working with Docker.'
