# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: update [OPTIONS] [VOLUME]
description: Update a volume (cluster volumes only)
flags:
    --availability=: Cluster Volume availability ("active", "pause", "drain")
documentation:
    command: |-
        [AI] `docker volume update` is a command used to modify the properties of Docker volumes, such as changing their labels or renaming them. This command does not create or delete volumes, it only updates existing ones. The general syntax for this command is:

        ```
        docker volume update [OPTIONS] NAME[/NAME]...
        ```

        For instance, to rename a volume from `myvol` to `newvol`, you can use the following command:

        ```
        docker volume update --rename myvol newvol
        ```

        To add or change labels on a volume, use the `--label` flag with key-value pairs:

        ```
        docker volume update myvol --label key1=value1 --label key2=value2
        ```

        This command doesn't affect the data contained within the volumes. It only modifies their metadata.
    flag:
        availability: '[AI] The `docker volume update --availability` command is used to modify the availability setting of a Docker volume. Availability can be set to one of three modes: `enabled`, `disabled`, or `external`. When set to `enabled`, the volume is managed by Docker and replicated across nodes in a swarm mode cluster. A `disabled` volume is not managed by Docker and its data persists only on the host where it was created. An `external` volume is managed by an external storage system and Docker just mounts it. This command helps to control how the data of your containers are replicated and managed across nodes in a swarm cluster.'
