# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: join-token [OPTIONS] (worker|manager)
description: Manage join tokens
flags:
    --rotate: Rotate join token
    -q, --quiet: Only display token
documentation:
    command: '[AI] `docker swarm join-token` is a command used to generate tokens for worker nodes to join a Docker Swarm cluster. When run, it produces a token and a CA certificate that can be used during the join process. The command supports different parameters like `is-manager` (to create manager tokens), `advertise-addr` (for setting the advertised IP address of the node), and `expiry-time` (for setting the expiration time of the token). Once a worker node joins the cluster using this token, it becomes part of the swarm and can participate in the container orchestration managed by the Docker Swarm manager.'
    flag:
        quiet: '[AI] The `docker swarm join-token --quiet` command is used to generate a TTL-expired Swarm join token in a quiet mode without any additional output or explanation. This command is typically used programmatically or in scripts, where the focus is on obtaining the token silently for joining worker nodes to an existing Docker Swarm cluster.'
        rotate: |-
            [AI] The `docker swarm join-token --rotate` command is used to generate a new token for joining Docker Swarm clusters. Swarm is a Docker orchestration tool that allows managing a cluster of Docker nodes as a single entity.

            The `--rotate` option causes the system to automatically rotate (generate a new) join token each time it's run, ensuring better security by preventing previously generated tokens from being used. The output will include the new token and the TLS-verified CA certificate for joining Swarm nodes securely.
