# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm [OPTIONS] NODE [NODE...]
aliases:
    - remove
description: Remove one or more nodes from the swarm
flags:
    -f, --force: Force remove a node from the swarm
documentation:
    command: '[AI] `docker node rm` is a command used with Docker Swarm mode to remove a worker node from the Swarm cluster. When executed, it takes the name or ID of the node as an argument and removes it from the cluster. The node will no longer be managed by the Swarm manager and its containers will be drained before being removed. This command should be used with caution to avoid disrupting running applications.'
    flag:
        force: '[AI] The command `docker node rm --force` is used to remove a worker node from a Swarm Mode cluster in Docker. The `--force` option is used to remove the node even if it''s currently hosting running services, which will be force-stopped before the node is removed. This command should only be used when you''re sure that removing the node won''t cause any issues with your Swarm cluster or the applications it hosts.'
