# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: service
description: Manage services
group: swarm
documentation:
    command: |-
        [AI] `docker service` is a subcommand used in Docker Swarm mode for managing and interacting with services, which are user-defined applications or microservices that run on multiple nodes in a swarm. The `docker service` command provides various options to:

        1. Create (`create`) and update (`update`) the configuration of services, including their networks, constraints, replicas count, etc.
        2. Inspect (`inspect`) the details of running or stopped services, such as their current state, network bindings, ports, and replica tasks.
        3. List (`ls`) all services currently deployed in a swarm, displaying their names, states, replicas count, and other relevant information.
        4. Scale (`scale`) the number of replicas for a service.
        5. Start (`start`) or stop (`stop`) specific services or their replica tasks.
        6. Remove (`rm`) a stopped service or service network.
