# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Manage Swarm configs
group: swarm
documentation:
    command: |-
        [AI] The `docker config` command is used to inspect, create, or update the user-defined settings of Docker images or containers. It allows you to modify various aspects such as labels, environment variables, and volumes without having to rebuild the image. You can also view the current configuration settings with the `inspect` option. The basic syntax is:

        ```
        docker config [OPTIONS] [IMAGE|CONTAINER] [NAME=VALUE|KEY=VALUE]
        ```

        Some common use cases include:

        1. Setting an environment variable for a container:
           ```
           docker config --add ENV_VAR="key value" CONTAINER_ID
           ```
        2. Updating a label on an image:
           ```
           docker config --update "com.example=value" IMAGE_NAME
           ```
        3. Inspecting the configuration of an image or container:
           ```
           docker config IMAGE_NAME | json_filter '.Config'
           ```
        4. Creating a new file in a Docker volume:
           ```
           docker config create --allow-none VOLUME_NAME FILE_PATH
           ```
