# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm MANIFEST_LIST [MANIFEST_LIST...]
description: Delete one or more manifest lists from local storage
documentation:
    command: '[AI] The `docker manifest rm` command is used to remove a specific layer or configuration from a Docker image manifest. A Docker image manifest is a JSON file that lists all the layers and configurations of an image. By using this command with the image name and tag, followed by the digest or index of the unwanted layer, you can delete it from the manifest. This can be useful when you want to modify or update specific layers in an image without rebuilding the entire image.'
