# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: info [OPTIONS]
description: Display system-wide information
flags:
    -f, --format=: Format the output using the given Go template
documentation:
    command: '[AI] `docker system info` is a Docker CLI (Command Line Interface) command used to display detailed information about the Docker daemon and the cluster it manages. This includes details such as the version of Docker, the operating system and architecture, the total and used storage capacity for images, containers, networks, and volumes, and the number and status of active nodes in the swarm mode cluster. This command provides a comprehensive overview of the current state of your Docker environment.'
    flag:
        format: |-
            [AI] `docker system info --format` is a command used in Docker to retrieve detailed information about the Docker daemon and the host system. The `--format` option allows specifying a custom template to format the output in a specific way, making it easier to parse and process programmatically.

            The output includes details such as the Docker version, operating system, total and usable storage space, active and total number of networks and images, and running and paused containers, among others. The custom template can be used to extract and display specific data fields in a desired format.
