# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm [OPTIONS] VOLUME [VOLUME...]
aliases:
    - remove
description: Remove one or more volumes
flags:
    -f, --force: Force the removal of one or more volumes
documentation:
    command: '[AI] The `docker volume rm` command is used to remove one or more named Docker volumes. When you run this command followed by the volume name, Docker will permanently delete the specified volume and all data it contains. If you want to remove multiple volumes, provide each volume name as an argument separately. Note that once a volume is deleted, the data inside cannot be recovered.'
    flag:
        force: '[AI] `docker volume rm --force` is a command used in Docker to permanently delete one or more named volumes. The `--force` option bypasses any read-write bindings and removes the data stored in those volumes, which cannot be recovered. This operation should only be performed when you are certain that the data stored in these volumes is no longer needed.'
