# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: ls [OPTIONS]
aliases:
    - list
description: List networks
flags:
    --format=: 'Format output using a custom template:'
    --no-trunc: Do not truncate the output
    -f, --filter=: Provide filter values (e.g. "driver=bridge")
    -q, --quiet: Only display network IDs
documentation:
    command: '[AI] `docker network ls` is a command used to list all the networks created in Docker. It shows details like network name, driver, size, and the number of containers connected to each network. This command helps users manage their Docker networking by providing an overview of existing networks.'
    flag:
        filter: '[AI] `docker network ls --filter` is a command used in Docker to list all defined networks along with certain filters. The `--filter` option allows you to specify specific criteria for the output. For instance, you can filter by name using `name=<network_name>`, or by driver using `driver=<driver_name>`. This command helps in managing and identifying networks based on desired characteristics.'
        format: '[AI] `docker network ls --format` is a command used to list all Docker networks along with custom output formatting. The `--format` option allows specifying a custom template for displaying the network information, which can include fields such as Network ID, Name, Driver, and Sc scope (scope: global or local to the swarm mode service). For example, `docker network ls --format ''table {{.Name}} {{.Driver}}''` will output the networks in a tabular format displaying their names and drivers.'
        no-trunc: '[AI] The `docker network ls --no-trunc` command is used to list all Docker networks in a system with truncated output suppressed. The output includes each network''s name, driver, and the number of attached containers or services. With the `--no-trunc` flag, the full length of the network names, which can sometimes be long when using custom drivers or complex overlay networks, are displayed without being truncated.'
        quiet: |-
            [AI] `docker network ls --quiet` is a command used in Docker to list all defined networks in a concise format. The `--quiet` option suppresses extra output and displays only the minimum necessary information, which includes the network name and driver. It returns an output with one line per network. For example:

            ```sh
            bridge  bridge
            host    host
            overlay overlay
            ```

            This command is helpful when writing scripts or automating tasks where you don't need extensive details about each network but just want a quick overview of the existing networks in your Docker environment.
