# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: install [OPTIONS] PLUGIN [KEY=VALUE...]
description: Install a plugin
flags:
    --alias=: Local name for plugin
    --disable: Do not enable the plugin on install
    --disable-content-trust: Skip image verification
    --grant-all-permissions: Grant all permissions necessary to run the plugin
documentation:
    command: '[AI] The `docker plugin install` command is used to install Docker plugins, also known as Docker Content-Trusted (DCT) plugins or Docker Engine Extensions. These plugins extend the functionality of Docker by adding new features or integrations with other tools. The command takes the plugin name and its repository as arguments, for example: `docker plugin install <plugin-name> <repository-url>`. It downloads and installs the plugin on the local Docker engine. After installation, the plugin can be used by creating a custom runtime using the `--plugins` flag when running `docker run`.'
    flag:
        alias: |-
            [AI] The `docker plugin install --alias` command is used to install a Docker plugin with a specified alias. The alias is an optional argument that allows users to easily call the plugin using a shorter name instead of its full name. For example, if you have a plugin named `myplugin`, and you want to install it with the alias `myp`, you would use:

            ```bash
            docker plugin install <plugin-repository>/<plugin-name>:<tag> --alias myp
            ```

            After running this command, you can call the plugin using the alias `myp` instead of the full name. For example:

            ```bash
            docker plugin use myp
            ```
        disable: '[AI] The `docker plugin install --disable` command is used to install a Docker plugin, but with the added flag `--disable`, it disables the plugin from being automatically started when Docker runs. This can be useful for managing plugins manually or for troubleshooting purposes. The plugin will still be installed, but it won''t be active until explicitly enabled later.'
        disable-content-trust: '[AI] The `docker plugin install --disable-content-trust` command is used to install a Docker plugin without enabling content trust. Content trust is a security feature in Docker that ensures the authenticity and integrity of plugins, images, and other artifacts. When you install a plugin with this option disabled, Docker will not verify the plugin''s contents against any trusted sources before using it. This can be useful if you want to use an untrusted plugin for testing or development purposes, but it is not recommended for production environments due to potential security risks.'
        grant-all-permissions: '[AI] The `docker plugin install --grant-all-permissions` command is used to install a Docker plugin with elevated permissions. The `--grant-all-permissions` flag grants the plugin all necessary permissions required to function effectively within the Docker environment, bypassing the default restrictions that would otherwise be applied. This command should be used with caution as it can potentially expose security vulnerabilities if used with untrusted plugins.'
