# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm CONFIG [CONFIG...]
aliases:
    - remove
description: Remove one or more configs
documentation:
    command: '[AI] `docker config rm` is a Docker command used to remove a specified configuration file from an image or container. The syntax is as follows: `docker config rm [OPTIONS] NAME`. Here, `NAME` refers to the name of the image or container followed by the configuration file name in the format `<image|container>:<config-file>`. This command does not delete the data associated with the configuration; it only removes the definition.'
