# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm NETWORK [NETWORK...]
aliases:
    - remove
description: Remove one or more networks
flags:
    -f, --force: Do not error if the network does not exist
documentation:
    command: '[AI] The `docker network rm` command is used to remove a Docker network. When you run this command followed by the network name, Docker will delete the specified network along with its associated subnet and gateway if it''s not in use. Networks that are currently being used cannot be deleted. If there are containers connected to the network, you must first disconnect or remove them before deleting the network.'
    flag:
        force: '[AI] The `docker network rm` command is used to remove a Docker network. The `--force` option is an optional flag that forces the removal of the network even if it''s still in use by one or more containers. When you run this command without any container using the network, it will be removed directly. But with the `--force` option, you can remove a network even if it''s still being used, and Docker will stop the containers that rely on it before removing the network. This might lead to data loss or other unintended consequences, so use this command carefully.'
