# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: build [OPTIONS] PATH | URL | -
description: Build an image from a Dockerfile
group: common
documentation:
    command: '[AI] `docker build` is a command used to construct Docker images from Dockerfiles. It reads the instructions from the Dockerfile in the current directory, or in a specified path, and builds the image using the base image and any additional layers defined in the Dockerfile. The resulting image can then be run as a container with `docker run`.'
