# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: wait CONTAINER [CONTAINER...]
description: Block until one or more containers stop, then print their exit codes
documentation:
    command: '[AI] `docker container wait` is a command used to block and wait for one or more containers to reach a healthy state based on their status code before continuing execution in the terminal. It monitors the specified container(s) and returns once they are all ready, making it useful when working with multi-container applications where services need to be available before further commands can be executed.'
