# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: ls [OPTIONS]
aliases:
    - list
description: List contexts
flags:
    --format=: 'Format output using a custom template:'
    -q, --quiet: Only show context names
documentation:
    command: '[AI] The `docker context ls` command is used to list all available contexts in Docker. A context represents a collection of Docker endpoints, keys, and networks that can be used to connect to multiple Docker hosts or clusters from a single client. The output shows each context''s name and the active (starred) context.'
    flag:
        format: '[AI] `docker context ls --format` is a command used in Docker to list all available contexts with custom formatting. Contexts represent different clusters of Docker engines, each with its own network and storage configuration. The `--format` option allows specifying the output format using Go templates. For example, `"table {{.Name}} {{.DockerHost}}"` will display a table with context name and Docker host.'
        quiet: '[AI] `docker context ls --quiet` is a command used in Docker to list all available contexts in a compact format. The `--quiet` flag tells Docker to output the results in plain text with minimal formatting, making it suitable for scripting or further processing by other tools. This command allows users to easily see and manage multiple contexts, each associated with its unique name and key pair, if used for TLS authentication.'
