# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: context
description: Manage contexts
group: management
documentation:
    command: '[AI] `docker context` is a Docker command used to manage contexts, which define the cluster or swarm of Docker environments that you can target when building or running applications. Contexts allow you to easily switch between different clusters, for example, for development and production use. You can create, delete, list, and inspect contexts using this command.'
