# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm [OPTIONS] PLUGIN [PLUGIN...]
aliases:
    - remove
description: Remove one or more plugins
flags:
    -f, --force: Force the removal of an active plugin
documentation:
    command: '[AI] The `docker plugin rm` command is used to remove a Docker plugin from your system. Plugins extend the functionality of Docker, and they are installed using the `docker plugin install` command. To uninstall or remove a plugin, use the `docker plugin rm` command followed by the name or ID of the plugin you wish to delete. For example: `docker plugin rm my-plugin`. This command removes the specified plugin from your Docker installation.'
    flag:
        force: '[AI] The `docker plugin rm` command is used to remove Docker plugins from a system. The `--force` option is used with this command to forcefully remove the plugin even if it''s in use by one or more containers or services. This means that any containers or services using the plugin will be stopped before the plugin can be removed, potentially causing downtime or other issues. It''s important to use this option carefully and only when you''re sure that removing the plugin won''t cause unintended consequences.'
