# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: prune [OPTIONS]
description: Remove all unused local volumes
flags:
    --filter=: Provide filter values (e.g. "label=<label>")
    -f, --force: Do not prompt for confirmation
documentation:
    command: '[AI] `docker volume prune` is a command used to remove unused and dangling volumes in Docker. It helps in managing and freeing up disk space by deleting volumes that are no longer needed or referenced by any container or image. By default, it removes all volumes that do not have an active container. Optionally, you can specify `-f` flag to force removal of volumes with active containers as well.'
    flag:
        filter: |-
            [AI] `docker volume prune` is a Docker command used to remove unused volumes. The `--filter` option allows you to apply filters when selecting which volumes to delete. With this option, you can specify certain conditions for the volumes, such as those that have no associated containers or are of a specific label. For example:

            - `--filter="dangling=true"` removes only dangling volumes (volumes without any associated containers)
            - `--filter="label=myapp=myproject"` removes only volumes with the specified label "myapp=myproject"

            By applying filters, you can choose to keep specific volumes while removing others, which helps ensure important data is not accidentally deleted.
        force: |-
            [AI] The `docker volume prune --force` command is used to remove unused and dangling Docker volumes permanently. Docker volumes are data storage areas for containers and applications. When a container is removed, its associated volumes may still occupy disk space unless they are explicitly deleted.

            The `prune` command identifies and marks the volumes for removal based on their usage. The `--force` flag is used to forcefully remove these marked volumes without any confirmation or error messages. This can lead to data loss if not used with caution, as it permanently deletes the selected volumes and their contents.
