# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: use CONTEXT
description: Set the current docker context
documentation:
    command: '[AI] The `docker context use` command is used to set a specific Docker context as the current context in Docker Desktop or Docker CLI. Contexts allow you to work with multiple Docker hosts, each with their own networks and services. By setting a context as current, you''ll be working against that host by default. For example, if you have two Docker hosts, one for development and another for production, you can switch between them using `docker context use`.'
