# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: load [OPTIONS] KEYFILE
description: Load a private key file for signing
flags:
    --name=: Name for the loaded key
documentation:
    command: '[AI] The `docker trust key load` command is used to import a GPG key into the Docker registry. This command allows you to manage and control access to your Docker registry using GPG keys for authentication. The key file should be in the standard GPG format (.gpg) and can be imported with this command by providing its file path as an argument. For example, `docker trust key load <key_file.gpg>`. After importing, you will need to set up the registry to use the new key for authentication.'
    flag:
        name: |-
            [AI] The `docker load` command is used to load a Docker image from a file or URL into your local Docker registry. The `--name` option specifies a name for the image after it has been loaded. The `docker trust key load` sub-command is used to load a GPG key into the Docker registry's trusted keys store. This allows you to verify the authenticity of images that have been signed with that key.

            So, the `docker trust key load --name <keyname> <keyfile.asc>` command loads a GPG key identified by `<keyfile.asc>` and gives it the name `<keyname>` in your Docker registry's trusted keys store.
