# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: port CONTAINER [PRIVATE_PORT[/PROTO]]
description: List port mappings or a specific mapping for the container
documentation:
    command: |-
        [AI] The `docker container port` command is used to publish or map a port from the Docker host to a container. The basic syntax is: `docker container PORT CONTAINER [OPTIONS]`. Replace `PORT` with the number of the port on the Docker host, and `CONTAINER` with the ID or name of the running container.

        For example, if you have a container named `my_container`, which listens on port 80 inside the container, you can publish this port to port 8080 on your Docker host by executing: `docker container port 8080 my_container`.

        Alternatively, you can map a specific port when starting the container using the `-p` or `--publish` option in the `docker run` command:

        ```bash
        docker run -it --name my_container image:latest -p 8080:80
        ```

        This maps the container's port 80 to your Docker host's port 8080. The `docker container port` command can be used to check or modify existing mappings.
