# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: create [OPTIONS] CONTEXT
description: Create a context
flags:
    --description=: Description of the context
    --docker=: set the docker endpoint
    --from=: create context from a named context
documentation:
    command: '[AI] `docker context create` is a Docker CLI command used to create a new context in Docker Desktop or Docker Client and switch to it. A context represents a cluster of Docker engines, which could be local or remote. Creating a context allows you to manage multiple environments, such as development, staging, and production, with ease. When creating a context, you can define its name and the endpoints (Docker hosts) that belong to it.'
    flag:
        description: |-
            [AI] `docker context create` is a command used in Docker to create a new context, which allows users to work with multiple clusters or environments, such as different hosts, registries, or networks, in a single Docker client. The `--description` option allows users to provide a description for the newly created context, making it easier to identify and manage multiple contexts. For example:

            ```sh
            $ docker context create my-new-context --description "My development environment"
            ```

            Creates a new context named `my-new-context` with the description `"My development environment"`. This makes it clear which context is intended for development work when working with multiple environments.
        docker: |-
            [AI] The `docker context create` command is used to create a new Docker context in Docker Desktop or Docker for Windows. A Docker context represents a set of Docker engines, networks, and volumes that you can use to work with different projects or environments.

            The `--docker` flag specifies that the new context should be associated with a specific Docker engine installation on your machine, rather than creating a new isolated engine instance. This means that any existing Docker daemon and its configurations will be used for this context. The command does not create a new engine but creates a new context to manage multiple engines or configurations.

            Here is an example of the command usage:
            ```
            docker context create <context-name> --docker <engine-name>
            ```
            Replace `<context-name>` with your desired name for the new context and `<engine-name>` with the name of the Docker engine you want to associate with it. This command creates a new context with that name and sets it as the active context, meaning any subsequent commands will use that context unless another one is explicitly specified.
        from: '[AI] `docker context create --from` is a command used in Docker to create a new context with an existing context or a remote context as its base. In other words, it allows you to clone or copy the configuration of one context to create a new one. This can be useful for creating consistent configurations across multiple environments or teams. The `--from` flag specifies the source context for the new context creation.'
