# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: 'add OPTIONS NAME REPOSITORY [REPOSITORY...] '
description: Add a signer
flags:
    --key=: Path to the signer's public key file
documentation:
    command: '[AI] The `docker trust` command is a sub-command of Docker''s Notary, which is a tool for managing and verifying the authenticity of images. The specific command you mentioned, `docker trust signer add`, is used to register a new signing key with the Notary server. This allows you to create new trusted repositories and sign Docker images. When this command is executed, it adds a new signing identity to the Notary server, which can then be used to sign images for distribution.'
    flag:
        key: '[AI] The `docker trust signer add --key` command is used to add a new signing key to the Docker Notary, which is a trusted registry for signing and verifying images. This command requires a key file in PEM format to be provided as an argument. Once added, this key can be used to sign and verify Docker images with increased security by ensuring their authenticity and integrity.'
