# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: inspect IMAGE[:TAG] [IMAGE[:TAG]...]
description: Return low-level information about keys and signatures
flags:
    --pretty: Print the information in a human friendly format
documentation:
    command: '[AI] The `docker trust inspect` command is used to display detailed information about a Docker registry or a specific trust on Docker Hub. It shows details such as the name, email, and username of the account that manages the registry or trust, the creation and modification dates, and the list of member groups and their members. This command helps in managing and maintaining the security of your Docker registry by providing transparency into who has access to it.'
    flag:
        pretty: '[AI] `docker trust inspect --pretty` is a command used in Docker to display detailed information about a Docker Registry or Trusted Registry in a human-readable format. It returns information such as the registry''s name, URL, insecure, signatures and signing keys. This command can help users verify the authenticity and security of the registry they are using to pull Docker images.'
