# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: remove [OPTIONS] NAME REPOSITORY [REPOSITORY...]
description: Remove a signer
flags:
    -f, --force: Do not prompt for confirmation before removing the most recent signer
documentation:
    command: '[AI] The `docker trust` subcommand is used to manage Docker Notary, a registry for signing and verifying images. The `signer remove` command is used to delete a specific signer from the trusted Anchors in Docker Registry. It removes the public key associated with the specified signer, revoking its trust and preventing the verification of any images signed by that key.'
    flag:
        force: '[AI] The `docker trust signer remove --force` command is used to permanently delete a trusted signing key from the Docker Registry. The `--force` option is used to bypass confirmation prompts, allowing for the deletion to occur without user intervention. This action cannot be undone and should only be executed after careful consideration, as removing a trusted signing key will cause any associated certificates or images to become invalid and may disrupt access to Docker content.'
