# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get REPO KEY
description: Get Git build environment key
documentation:
    command: '[AI] The `git config get` command is used to retrieve the value of a specific Git configuration variable. It takes the name of the variable as an argument and prints its value to the console. For example, `git config get user.name` would print the value configured for the "user.name" variable.'
