# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config REPO
description: Configure Git build
documentation:
    command: |-
        [AI] The `git config` command is used to set or view the configuration variables for Git, which is a popular version control system. The command can be followed by various options:

        * `git config <key> <value>` sets the specified configuration variable with the given value. For example, `git config user.name "Your Name"`.
        * `git config --list` lists all the current Git configuration variables and their values.
        * `git config --global <key> <value>` sets the configuration variable globally for all repositories on the current system (as opposed to setting it for a specific repository). For example, `git config --global user.name "Your Name"`.
        * Without any arguments, `git config` displays the value of the 'user' configuration variable by default, which includes the name and email used in commits.
