# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: unset REPO KEY
description: Remove Git build environment key
documentation:
    command: '[AI] The `git config unset` command is used to remove or unset a specific Git configuration variable. The `fury` part of the command is likely just a typo, as this command is typically used without it. To use it correctly, specify the name of the configuration option you want to unset. For example, `git config unset user.email`. This will remove the specified Git configuration setting, allowing it to revert back to its default value or be empty.'
