name: forget
description: Forget a previously authenticated forge account
flags:
    -h, --help: Print help (see more with '--help')
documentation:
    command: |
        Forget a previously authenticated forge account.

        Examples

        Forget a specific account:

          but config forge forget username

        Interactively select which account(s) to forget:

          but config forge forget
    flag:
        help: Print help (see a summary with '-h')
