# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Get or set the configuration of a Dagger module
group: module
persistentflags:
    --focus: Only show output for focused commands
    -m, --mod=: Path to dagger.json config file for the module or a directory containing that file. Either local path (e.g. "/path/to/some/dir") or a github repo (e.g. "github.com/dagger/dagger/path/to/some/subdir")
documentation:
    command: '[AI] `dagger config` is a Dagger-related command used in the context of building and managing projects using the Dagger dependency injection framework for Java or Kotlin. This command is utilized to configure various aspects of your Dagger project, such as specifying the application modules, dependencies, and other build settings. It interacts with `dagger.build.dsl` files, which define the configuration for the Dagger compilation process. The exact usage of this command depends on the specific setup of your project and the version of Dagger being used. For more detailed information, refer to the official Dagger documentation.'
