name: delete
description: Delete a connection.
flags:
    --application-template=: The applicationTemplate id of the connection resource.
    --component=: The component id of the connection resource.
    --location=: The location id of the connection resource.
    --space=: The space id of the connection resource.
documentation:
    command: Delete a connection between components in an application template.
    flag:
        application-template: |-
            The applicationTemplate id of the connection resource.
            +
            To set the `application-template` attribute:
            * provide the argument `connection` on the command line with a fully specified name;
            * provide the argument `--application-template` on the command line.
        component: |-
            The component id of the connection resource.
            +
            To set the `component` attribute:
            * provide the argument `connection` on the command line with a fully specified name;
            * provide the argument `--component` on the command line.
        location: |-
            The location id of the connection resource.
            +
            To set the `location` attribute:
            * provide the argument `connection` on the command line with a fully specified name;
            * provide the argument `--location` on the command line.
        space: |-
            The space id of the connection resource.
            +
            To set the `space` attribute:
            * provide the argument `connection` on the command line with a fully specified name;
            * provide the argument `--space` on the command line.
