name: disable
description: '*(BETA)*  Disable Multi-cluster Ingress Feature.'
flags:
    --force: Force disablement.
    --no-force&: Force disablement.
documentation:
    command: |-
        *(BETA)*  This command disables Multi-cluster Ingress Feature in a fleet.

        ## EXAMPLES

        To disable the Ingress Feature, run:

          $ gcloud beta container fleet ingress disable
    flag:
        force: Force disablement. Bypasses any prompts for confirmation. When disabling the entire feature, proceeds even if the feature is in use. Might result in unexpected behavior.
        no-force: Force disablement. Bypasses any prompts for confirmation. When disabling the entire feature, proceeds even if the feature is in use. Might result in unexpected behavior.
