name: deployments
description: '*(ALPHA)*  Commands for Deployment Manager deployments.'
documentation:
    command: '*(ALPHA)*  Commands to create, update, delete, and examine deployments of resources.'
