name: snapshot-settings
description: '*(ALPHA)*  Describe and update Compute Engine snapshot settings.'
documentation:
    command: |
        *(ALPHA)*  Describe and update Compute Engine snapshot settings.
