name: vpc-flow-logs-configs
description: Manage the VPC Flow Logs configurations.
documentation:
    command: |-
        The flag --location=global is required for all the commands.

        You can either specify resources for project-level configurations, or use the
        --organization flag to apply organization-level configurations.
