name: config
description: '*(ALPHA)*  Manage Access Context Manager service perimeter configurations.'
documentation:
    command: '*(ALPHA)*  Manage Access Context Manager service perimeter configurations.'
