name: create
description: '*(ALPHA)*  Create an application.'
flags:
    --app-parameters=: A list of parameters to attach to the deployment source object, which is a
    --attributes-business-owners=: Business team that ensures user needs are met and value is delivered.
    --attributes-developer-owners=: Developer team that owns development and coding.
    --attributes-operator-owners=: Operator team that ensures runtime and operations.
    --component-parameters=: A list of component parameters to associate with the application.
    --connection-configs=: Connection configuration for the application.
    --criticality-level=: Criticality level.
    --criticality-mission-critical: Indicates mission-critical Application, Service, or Workload.
    --criticality-type=!: Criticality Type.
    --deployment-project=: Deployment project of the application.
    --deployment-region=: The region where the application is deployed.
    --description=: Description of the application.
    --display-name=: Display name of the application.
    --environment-type=!: Environment Type.
    --environment=: Environment name.
    --gke-deployment-target-cluster-self-link=!: The self link of the cluster where GKE based application is deployed.
    --gke-deployment-target-kubernetes-service-account=!: The kubernetes service account that is created within the namespace
    --gke-deployment-target-namespace=!: The namespace where the application is deployed.
    --import-existing-resources: Import existing resources into the application.
    --location=: The location id of the application resource.
    --no-criticality-mission-critical&: Indicates mission-critical Application, Service, or Workload.
    --no-import-existing-resources&: Import existing resources into the application.
    --scope-type=!: Scope Type.
    --service-account=: Your own service account that you use to deploy an application.
    --source-application-template-revision=: Application template revision URI.
    --source-shared-template-revision-uri=: Shared template revision URI.
    --space=: The space id of the application resource.
    --type=: The type of the application.
completion:
    flag:
        criticality-type:
            - high
            - low
            - medium
            - mission-critical
        environment-type:
            - development
            - production
            - staging
            - test
        scope-type:
            - global
            - regional
        type:
            - helm-app
            - terraform-app
documentation:
    command: '*(ALPHA)*  Create an application in a space.'
    flag:
        app-parameters: |-
            A list of parameters to attach to the deployment source object, which is a
            catalog entry or application template snapshot.
            +
            *key*:::
            The key of the parameter.
            +
            *value*:::
            The value of the parameter.
            +
            :::
            *Shorthand Example:*
            +
            ```
            +
            --app-parameters=key=string,value={...} --app-parameters=key=string,value={...}
            +
            ```
            +
            *JSON Example:*
            +
            ```
            +
            --app-parameters='[{"key": "string", "value": {...}}]'
            +
            ```
            +
            *File Example:*
            +
            ```
            +
            --app-parameters=path_to_file.(yaml|json)
            +
            ```
        attributes-business-owners: |-
            Business team that ensures user needs are met and value is delivered.
            +
            *channel*:::
            Communication channel of the contacts.
            +
            *uri*::::
            URI of the channel.
            +
            *displayName*:::
            Contact's name.
            Can have a maximum length of 63 characters.
            +
            *email*:::
            Email address of the contacts.
            +
            :::
            *Shorthand Example:*
            +
            ```
            +
            --attributes-business-owners=channel={uri=string},displayName=string,email=string --attributes-business-owners=channel={uri=string},displayName=string,email=string
            +
            ```
            +
            *JSON Example:*
            +
            ```
            +
            --attributes-business-owners='[{"channel": {"uri": "string"}, "displayName": "string", "email": "string"}]'
            +
            ```
            +
            *File Example:*
            +
            ```
            +
            --attributes-business-owners=path_to_file.(yaml|json)
            +
            ```
        attributes-developer-owners: |-
            Developer team that owns development and coding.
            +
            *channel*:::
            Communication channel of the contacts.
            +
            *uri*::::
            URI of the channel.
            +
            *displayName*:::
            Contact's name.
            Can have a maximum length of 63 characters.
            +
            *email*:::
            Email address of the contacts.
            +
            :::
            *Shorthand Example:*
            +
            ```
            +
            --attributes-developer-owners=channel={uri=string},displayName=string,email=string --attributes-developer-owners=channel={uri=string},displayName=string,email=string
            +
            ```
            +
            *JSON Example:*
            +
            ```
            +
            --attributes-developer-owners='[{"channel": {"uri": "string"}, "displayName": "string", "email": "string"}]'
            +
            ```
            +
            *File Example:*
            +
            ```
            +
            --attributes-developer-owners=path_to_file.(yaml|json)
            +
            ```
        attributes-operator-owners: |-
            Operator team that ensures runtime and operations.
            +
            *channel*:::
            Communication channel of the contacts.
            +
            *uri*::::
            URI of the channel.
            +
            *displayName*:::
            Contact's name.
            Can have a maximum length of 63 characters.
            +
            *email*:::
            Email address of the contacts.
            +
            :::
            *Shorthand Example:*
            +
            ```
            +
            --attributes-operator-owners=channel={uri=string},displayName=string,email=string --attributes-operator-owners=channel={uri=string},displayName=string,email=string
            +
            ```
            +
            *JSON Example:*
            +
            ```
            +
            --attributes-operator-owners='[{"channel": {"uri": "string"}, "displayName": "string", "email": "string"}]'
            +
            ```
            +
            *File Example:*
            +
            ```
            +
            --attributes-operator-owners=path_to_file.(yaml|json)
            +
            ```
        component-parameters: |-
            A list of component parameters to associate with the application.
            +
            *component*:::
            The name of the component parameter.
            +
            *parameters*:::
            A list of parameters associated with the component.
            +
            *key*::::
            The key of the parameter.
            +
            *value*::::
            The value of the parameter.
            +
            :::
            *Shorthand Example:*
            +
            ```
            +
            --component-parameters=component=string,parameters=[{key=string,value={...}}] --component-parameters=component=string,parameters=[{key=string,value={...}}]
            +
            ```
            +
            *JSON Example:*
            +
            ```
            +
            --component-parameters='[{"component": "string", "parameters": [{"key": "string", "value": {...}}]}]'
            +
            ```
            +
            *File Example:*
            +
            ```
            +
            --component-parameters=path_to_file.(yaml|json)
            +
            ```
        connection-configs: |-
            Connection configuration for the application.
            +
            *connectionUri*:::
            The connection URI.
            +
            *destinationComponentParameters*:::
            The parameters of the connection associated with the destination component.
            +
            *key*::::
            The key of the parameter.
            +
            *value*::::
            The value of the parameter.
            +
            *sourceComponentParameters*:::
            The parameters of the connection associated with the source component.
            +
            *key*::::
            The key of the parameter.
            +
            *value*::::
            The value of the parameter.
            +
            :::
            *Shorthand Example:*
            +
            ```
            +
            --connection-configs=connectionUri=string,destinationComponentParameters=[{key=string,value={...}}],sourceComponentParameters=[{key=string,value={...}}] --connection-configs=connectionUri=string,destinationComponentParameters=[{key=string,value={...}}],sourceComponentParameters=[{key=string,value={...}}]
            +
            ```
            +
            *JSON Example:*
            +
            ```
            +
            --connection-configs='[{"connectionUri": "string", "destinationComponentParameters": [{"key": "string", "value": {...}}], "sourceComponentParameters": [{"key": "string", "value": {...}}]}]'
            +
            ```
            +
            *File Example:*
            +
            ```
            +
            --connection-configs=path_to_file.(yaml|json)
            +
            ```
        criticality-level: |-
            Criticality level.
            Can contain only lowercase letters, numeric characters,
            underscores, and dashes. Can have a maximum length of 63 characters.
            Deprecated: Please refer to type instead.
        criticality-mission-critical: |-
            Indicates mission-critical Application, Service, or Workload.
            Deprecated: Please refer to type instead.
        criticality-type: |-
            Criticality Type. _CRITICALITY_TYPE_ must be one of:
            +
            *high*::: High impact.
            *low*::: Low impact.
            *medium*::: Medium impact.
            *mission-critical*::: Mission critical service, application or workload.
            :::
            +
        deployment-project: Deployment project of the application.
        deployment-region: The region where the application is deployed.
        description: Description of the application.
        display-name: Display name of the application.
        environment: |-
            Environment name.
            Can contain only lowercase letters, numeric characters,
            underscores, and dashes. Can have a maximum length of 63 characters.
            Deprecated: Please refer to type instead.
        environment-type: |-
            Environment Type. _ENVIRONMENT_TYPE_ must be one of:
            +
            *development*::: Development environment.
            *production*::: Production environment.
            *staging*::: Staging environment.
            *test*::: Test environment.
            :::
            +
        gke-deployment-target-cluster-self-link: The self link of the cluster where GKE based application is deployed.
        gke-deployment-target-kubernetes-service-account: |-
            The kubernetes service account that is created within the namespace
            provided above.
            Example: default or node-sa
        gke-deployment-target-namespace: The namespace where the application is deployed.
        import-existing-resources: Import existing resources into the application.
        location: |-
            The location id of the application resource.
            +
            To set the `location` attribute:
            * provide the argument `application` on the command line with a fully specified name;
            * provide the argument `--location` on the command line.
        no-criticality-mission-critical: |-
            Indicates mission-critical Application, Service, or Workload.
            Deprecated: Please refer to type instead.
        no-import-existing-resources: Import existing resources into the application.
        scope-type: |-
            Scope Type. _SCOPE_TYPE_ must be one of:
            +
            *global*::: Global type.
            *regional*::: Regional type.
            :::
            +
        service-account: Your own service account that you use to deploy an application.
        source-application-template-revision: Application template revision URI.
        source-shared-template-revision-uri: Shared template revision URI.
        space: |-
            The space id of the application resource.
            +
            To set the `space` attribute:
            * provide the argument `application` on the command line with a fully specified name;
            * provide the argument `--space` on the command line.
        type: |-
            The type of the application. _TYPE_ must be one of:
            +
            *helm-app*::: Application type is helm application.
            *terraform-app*::: Application type is terraform application.
            :::
            +
