name: resource-config
description: '*(ALPHA)*  Commands for declarative management of Google Cloud Platform resources.'
documentation:
    command: '*(ALPHA)*  Commands for declarative management of Google Cloud Platform resources.'
