name: import-statefile
description: Import a terraform state file.
flags:
    --file=: File path for importing statefile into a deployment.
    --location=: The Cloud location for the deployment.
    --lock-id=!: Lock ID of the lock file to verify person importing owns lock.
documentation:
    command: This command generates a signed url to upload a terraform state file.
    flag:
        file: |-
            File path for importing statefile into a deployment. It specifies the
            local file path of an existing Terraform statefile to directly upload
            for a deployment.
        location: |-
            The Cloud location for the deployment.
            +
            To set the `location` attribute:
            * provide the argument `DEPLOYMENT` on the command line with a fully specified name;
            * provide the argument `--location` on the command line;
            * set the property `infra-manager/location`.
        lock-id: Lock ID of the lock file to verify person importing owns lock.
