name: multicloud-data-transfer-configs
description: '*(BETA)*  Manage Multicloud Data Transfer Config resources.'
documentation:
    command: '*(BETA)*  Manage Multicloud Data Transfer Config resources.'
