name: delete
description: '*(BETA)*  Deletes a named configuration.'
documentation:
    command: |
        *(BETA)*  Deletes a named configuration. You cannot delete a configuration that is active, even
        when overridden with the --configuration flag.  To delete the current
        active configuration, first `gcloud config configurations activate`
        another one.

        See `gcloud topic configurations` for an overview of named
        configurations.
