name: deployments
description: Manage deployments of Apigee API proxies in runtime environments.
documentation:
    command: |
        Manage deployments of Apigee API proxies in runtime environments.

        `gcloud apigee deployments` contains commands for enumerating and checking the status
        of deployments of proxies to runtime environments.
