name: settings
description: '*(BETA)*  The command group for Cloud Quotas AdjusterSettings.'
documentation:
    command: |-
        *(BETA)*  A QuotaAdjusterSettings resource represents your adjuster setting for a
        particular project. Enable this to automatically adjust quotas.
