# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config SUBCOMMAND
description: Modify kubeconfig files
persistentflags:
    --kubeconfig=: use a particular kubeconfig file
documentation:
    command: '[AI] `kubectl config` is a command-line interface tool used to manage configuration settings for the Kubernetes cluster and its contexts in the `kubeconfig` file. It includes various subcommands for creating, editing, deleting, or retrieving different configurations such as `create-cluster-role`, `current-context`, `edit-context`, `get-clusters`, etc. These actions help users to customize their Kubernetes experience and work with multiple clusters in their environment.'
