# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: delete-context NAME
description: Delete the specified context from the kubeconfig
documentation:
    command: '[AI] The `kubectl config delete-context` command is used to remove a specific Kubernetes context from your local `kubeconfig` file. Contexts in Kubernetes represent clusters or environments, and deleting a context removes the configuration associated with it, effectively disconnecting from that particular cluster or environment.'
