# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get-clusters
description: Display clusters defined in the kubeconfig
documentation:
    command: '[AI] The `kubectl config get-clusters` command is used to retrieve information about the clusters configured in your Kubernetes `kubeconfig` file. This command does not interact with any clusters directly, but instead displays metadata about each cluster such as its name, server address, and certificate authorities. It allows you to view and manage multiple Kubernetes clusters from a single `kubeconfig` file.'
