# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rename-context CONTEXT_NAME NEW_NAME
description: Rename a context from the kubeconfig file
documentation:
    command: |-
        [AI] `kubectl config rename-context` is a Kubernetes command used to rename an existing context in your Kubeconfig file. This command modifies the name of a context without affecting other configurations. It's helpful when you need to change the name of a context for organizational or configuration purposes.

        The general syntax is: `kubectl config rename-context <old-context> <new-context>`

        Replace `<old-context>` with the current name of the context, and `<new-context>` with the desired new name. Keep in mind that this command only updates the context's name; it doesn't modify any clusters or user information associated with the context.
