# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: delete-user NAME
description: Delete the specified user from the kubeconfig
documentation:
    command: '[AI] `kubectl config delete-user` is a command used in Kubernetes to delete an existing user configuration from the current kubeconfig file. The kubeconfig file stores authentication and cluster information for using `kubectl`, the Kubernetes command-line tool. By deleting a user, you remove their access to your Kubernetes clusters managed by that particular config. Note that this action is irreversible, so be cautious when using it.'
