# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: use-context CONTEXT_NAME
aliases:
    - use
description: Set the current-context in a kubeconfig file
documentation:
    command: '[AI] The `kubectl config use-context` command in Kubernetes is used to set the current context for the `kubectl` configuration. Contexts represent different clusters or configurations, and by switching between them, you can manage resources across multiple environments. For instance, if you have clusters in different regions or projects, you can switch between them using this command. By doing so, `kubectl` will use the corresponding cluster''s configuration when executing commands.'
