# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: current-context
description: Display the current-context
documentation:
    command: '[AI] `kubectl config current-context` is a Kubernetes command used to display the name of the currently active Kubernetes cluster context in the local kubeconfig file. It helps users identify which cluster they are currently working against in their Kubernetes environment.'
