# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: unset PROPERTY_NAME
description: Unset an individual value in a kubeconfig file
documentation:
    command: |-
        [AI] `kubectl config unset` is a command used in Kubernetes to remove or delete specific key-value pairs from the current kubeconfig file. This command modifies the user's local kubeconfig, which holds authentication and cluster information for `kubectl`. By specifying the key name as an argument, you can delete its corresponding value from the configuration. For example:

        ```bash
        $ kubectl config unset myKey
        ```

        This command removes the 'myKey' entry and its associated value in the kubeconfig file. Note that this operation only affects the local kubeconfig, and any changes will not persist across different systems unless you synchronize the configuration accordingly.
