# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: delete-cluster NAME
description: Delete the specified cluster from the kubeconfig
documentation:
    command: '[AI] The `kubectl config delete-cluster` command is used to remove a Kubernetes cluster configuration from your local `kubeconfig` file. This command erases all data related to that specific cluster, including its name and server address. Once deleted, you will no longer be able to manage resources in that cluster using `kubectl` unless you re-add the configuration.'
