# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get-users
description: Display users defined in the kubeconfig
documentation:
    command: '[AI] The `kubectl config get-users` command is used to list the current Kubernetes configuration contexts and their associated user profiles in the local kubeconfig file. It does not directly list "users" in the sense of individual Kubernetes users with RBAC roles, but rather it lists the active context and the user profiles associated with that context. These user profiles represent sets of authentication and authorization information used to access clusters or namespaces within a cluster.'
