# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get
description: Echo the config values to stdout
documentation:
    command: '[AI] `npm config get` is a command used in Node.js package management with npm (Node Package Manager). This command retrieves the value of an npm configuration variable. For instance, `npm config get init-author-name` would return the author name set for your npm projects.'
