# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set
description: Sets each of the config keys to the value provided
documentation:
    command: '[AI] `npm config set` is a command used in Node.js package management with npm (Node Package Manager) to configure global project-specific settings or modify existing ones. The syntax is: `npm config set <key> <value>`, where `<key>` is the name of the configuration variable and `<value>` is the desired value. For example, `npm config set save-exact true` sets the global "save-exact" option to true. These configurations persist across npm installations unless changed.'
