# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
description: Show all the config settings
flags:
    --json: output as json
documentation:
    command: '[AI] The `npm config list` command is used to display all the user-level and global configuration variables set in Node Package Manager (npm). It lists the name, value, and whether it''s a user or global setting for each configuration variable. This can be helpful when debugging or managing npm configurations.'
    flag:
        json: '[AI] `npm config list --json` is a command used in Node.js package management with npm (Node Package Manager). This command returns an JSON object containing all the current user-level and global configuration settings of npm. It provides a clear, machine-readable output that can be easily parsed by scripts or other applications. In summary, it lists out all the NPM configs in JSON format.'
