# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: delete
description: Deletes the specified keys from all configuration files
documentation:
    command: '[AI] The `npm config delete` command is used to remove a specific configuration setting from your Node.js package manager (npm) global or project-level configuration file. For instance, you can use it to delete a custom registry, change the save or prefix keys, among others. The command takes the name of the configuration variable as an argument and deletes it accordingly. For example: `npm config delete save-exact`.'
