# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: edit
description: Opens the config file in an editor
flags:
    --editor=: editor to use
documentation:
    command: '[AI] `npm config edit` is a command used with npm (Node Package Manager) to open the npm configuration file, usually located in `~/.npmrc` on Unix-based systems or `%USERPROFILE%\.npmrc` on Windows, in a text editor for editing. This allows users to modify or add custom configuration settings as needed.'
    flag:
        editor: '[AI] `npm config edit --editor` is a command used in Node.js package manager (npm) to configure and set the default text editor for use with various npm commands, such as `npm install`, `npm init`, etc. By running this command, the user will be presented with an interactive text editor session where they can edit the `~/.npmrc` file and add or modify the `editor.cmd` property to set their preferred text editor. For example, setting it to "code" would configure npm to use Visual Studio Code as the default editor for editing package JSON files.'
