# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Manage the npm configuration files
persistentflags:
    -g, --global: operate in global mode
documentation:
    command: '[AI] `npm config` is a command used in Node.js package management system, npm, to configure various settings. It can be used to view, edit or set up global and project-specific configuration options. For instance, `npm config get <key>` retrieves the value of a specific key, while `npm config set <key> <value>` sets a new configuration variable. Additionally, there''s `npm config ls` to list all the configurations.'
