# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: kubeconfig
description: Kubeconfig file utilities
documentation:
    command: '[AI] `kubeadm kubeconfig` is a subcommand used with Kubeadm, an open-source project for deploying and managing Kubernetes clusters. This command generates and configures various Kubernetes client configuration files, including the `kube-config` file which allows users to interact with their cluster using tools like `kubectl`. The generated configurations can be used to authenticate and communicate with the Kubernetes master node.'
