# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: pull
description: Pull images used by kubeadm
persistentflags:
    --config=: Path to a kubeadm configuration file.
    --cri-socket=: Path to the CRI socket to connect. If empty kubeadm will try to auto-detect this value; use this option only if you have more than one CRI installed or if you have non-standard CRI socket.
    --feature-gates=: A set of key=value pairs that describe feature gates for various features.
    --image-repository=: Choose a container registry to pull control plane images from
    --kubernetes-version=: Choose a specific Kubernetes version for the control plane.
documentation:
    command: '[AI] The `kubeadm config images pull` command is used to pull and update the container images that are required to run Kubernetes components such as the Kubernetes apiserver, etcd, kubelet, and other related components. It ensures that the images used by Kubeadm are up-to-date with the latest versions from the official Kubernetes registry. This command is usually executed during the initial setup of a Kubernetes cluster or when updating an existing one to maintain security and stability.'
