# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: print
description: Print configuration
documentation:
    command: '[AI] `kubeadm config print` is a command used to retrieve the current configuration of a Kubernetes cluster managed by Kubeadm. This includes cluster initialization configurations such as API server certificates, control plane node configuration, and join tokens for worker nodes. The output can be saved to a file or printed directly to the terminal, providing transparency and enabling backup or modification of the configuration if needed.'
