# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: kubeconfig
description: Generate all kubeconfig files necessary to establish the control plane and the admin kubeconfig file
documentation:
    command: '[AI] The `kubeadm init` command is used to bootstrap a new Kubernetes cluster. When you run this command with the argument `phase kubeconfig`, it generates and configures the `kubeconfig` file for the current user on the machine where `kubeadm init` was executed. This file allows users to interact with the Kubernetes cluster using `kubectl`. After generating the `kubeconfig` file, you can use `kubectl` to manage and deploy applications in your newly created cluster.'
