# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: upload-config
description: Upload the kubeadm and kubelet configuration to a ConfigMap
documentation:
    command: '[AI] `kubeadm init phase upload-config` is a subcommand used to initiate the process of uploading the Kubernetes configuration files to a non-privileged user on a node during the initial setup of a Kubernetes cluster using kubeadm. These files include the certificate authorities, client certificates, and the kubeconfig file that allow communication with the Kubernetes control plane. This command sets up the environment for a non-root user to join the cluster as a regular worker node.'
