# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Manage configuration for a kubeadm cluster persisted in a ConfigMap in the cluster
persistentflags:
    --kubeconfig=: The kubeconfig file to use when talking to the cluster. If the flag is not set, a set of standard locations can be searched for an existing kubeconfig file.
documentation:
    command: |-
        [AI] `kubeadm config` is a command used in Kubernetes to generate or manipulate various Kubernetes cluster configuration files. It's part of the Kubeadm tool, which is used for bootstrapping and managing a Kubernetes cluster.

        The specific usage of this command depends on its sub-commands:

        1. `kubeadm config init`: Generates the initial configuration files required to bootstrap a new Kubernetes master node. It sets up the required certificates, Kubernetes configuration, and other necessary files.

        2. `kubeadm config view`: Shows the current configuration of a Kubernetes cluster, including the API server's certificate, cluster status, and control plane components.

        3. `kubeadm config print kubeconfig [<flags>]`: Generates the kubeconfig file that can be used to interact with the Kubernetes cluster. It includes the necessary context and current-context definitions.

        4. `kubeadm config set [key]=[value] [configfile]`: Modifies the provided Kubernetes configuration file by updating a specific key-value pair, such as the server address or certificate authorization data.

        5. `kubeadm config to-raw [configfile] > raw_output.yaml`: Converts an existing Kubernetes configuration file into a plain text format suitable for embedding in other YAML files or scripts.
