# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get
description: Read a configuration settings
flags:
    --json: Format the output as an NDJSON stream
    --no-redacted: Don't redact secrets (such as tokens) from the output
documentation:
    command: '[AI] The `yarn config get` command is used to retrieve the value of a specific configuration key in your Yarn (JavaScript package manager) project. For instance, you can use it to view the current value of the repository or cache folder location by running `yarn config get <key-name>`. This command helps manage and understand your project configurations within the Yarn environment.'
    flag:
        json: |-
            [AI] `yarn config get --json` is a command used in Yarn, a popular JavaScript package manager. This command retrieves the value of a specific Yarn configuration variable in JSON format. For example, if you have set up a proxy for your network requests in your Yarn configuration file (`.yarnrc` or `yarn.lock`), you can use this command to get the proxy settings as a JSON object:

            ```sh
            $ yarn config get proxy --json
            {"proxy":"http://your-proxy-address:port"}
            ```
        no-redacted: '[AI] `yarn config get` is a command used in Yarn package manager to retrieve the value of a specific configuration key. The `--no-redacted` flag is an optional argument that instructs Yarn not to redact sensitive information, such as authentication tokens or passwords, from the output when displaying the configuration value. By default, Yarn hides such information for security reasons. Without the `--no-redacted` flag, only the masked parts of the sensitive data will be displayed.'
