# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: unset
description: Unset a configuration setting
flags:
    -H, --home: Update the home configuration instead of the project configuration
documentation:
    command: '[AI] `yarn config unset` is a Yarn command used to unset (remove) specific configurations from the Yarn global or project-level `.yarnrc` file. When you run this command followed by the configuration key, Yarn will remove that particular configuration key and value, allowing the default behavior to take effect. For instance, to unset a configuration named `foo`, use: `yarn config unset foo`.'
    flag:
        home: '[AI] The command `yarn config unset --home` is used to unset (remove) the Yarn global configuration option named `--home`. This configuration option specifies the location of Yarn''s global installation directory. Running this command will reset Yarn''s global configuration to its default value, allowing future installations and configurations to use the system-wide Node.js installation or any other specified location.'
