# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Interact with Consul's Centralized Configurations
documentation:
    command: '[AI] `consul config` is a command provided by Consul, an open-source distributed configuration and service discovery solution. This command is used to load or save configuration data from or into Consul''s key-value store (known as KV). By default, it loads the configuration data for a given key, which can include application settings, secrets, or other custom data. If you provide an output file, it will save the configuration data to that location.'
