# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
description: List centralized config entries of a given kind
flags:
    --kind=: The kind of configurations to list.
    --namespace=: Specifies the namespace to query.
documentation:
    command: '[AI] The `consul config list` command is used in Consul, a popular service discovery and configuration management tool, to display the current configuration items and their values that are stored in the Consul Key-Value store (KV). This command helps users to easily view and manage the configuration data within the Consul environment.'
    flag:
        kind: '[AI] The `consul config list --kind` command is used with the Consul configuration management tool. This command lists all configuration items in the Consul server or a specific service, based on their type or kind. The `--kind` flag filters the output to only show configurations of the specified type (e.g., `network`, `service`, `keyvalue`). By providing the correct type, you can easily view and manage specific configuration items within the Consul system.'
        namespace: |-
            [AI] The `consul config list --namespace` command is used in Hashicorp Consul, a service discovery and configuration management tool. This command lists all the configurations that are stored in Consul under a specific namespace.

            When you run this command without any arguments, it will list all the configurations across all namespaces. However, by providing a namespace argument, you can filter the output to display only the configurations belonging to that particular namespace. This is useful when working with multiple applications or teams, each having their own distinct configuration data in Consul.
