name: update-cluster-configuration
description: Updates the cluster with the configuration that is specified in the request body.
flags:
    --cluster-arn=!: The Amazon Resource Name (ARN) that uniquely identifies the cluster.
    --configuration-info=!: Represents the configuration that you want MSK to use for the brokers in a cluster.
    --current-version=!: The version of the cluster that needs to be updated.
documentation:
    command: Updates the cluster with the configuration that is specified in the request body.
    flag:
        cluster-arn: The Amazon Resource Name (ARN) that uniquely identifies the cluster.
        configuration-info: Represents the configuration that you want MSK to use for the brokers in a cluster.
        current-version: The version of the cluster that needs to be updated.
