name: modify-replication-config
description: Modifies an existing DMS Serverless replication configuration that you can use to start a replication.
flags:
    --cli-input-json=: Read arguments from the JSON string provided.
    --cli-input-yaml=: Read arguments from the YAML string provided.
    --compute-config=: Configuration parameters for provisioning an DMS Serverless replication.
    --generate-cli-skeleton: Prints a JSON skeleton to standard output without sending an API request.
    --replication-config-arn=!: The Amazon Resource Name of the replication to modify.
    --replication-config-identifier=: The new replication config to apply to the replication.
    --replication-settings=: The settings for the replication.
    --replication-type=: The type of replication.
    --source-endpoint-arn=: The Amazon Resource Name (ARN) of the source endpoint for this DMS serverless replication configuration.
    --supplemental-settings=: Additional settings for the replication.
    --table-mappings=: Table mappings specified in the replication.
    --target-endpoint-arn=: The Amazon Resource Name (ARN) of the target endpoint for this DMS serverless replication configuration.
completion:
    flag:
        replication-type:
            - full-load
            - cdc
            - full-load-and-cdc
documentation:
    command: |-
        Modifies an existing DMS Serverless replication configuration that you can use to start a replication. This command includes input validation and logic to check the state of any replication that uses this configuration. You can only modify a replication configuration before any replication that uses it has started. As soon as you have initially started a replication with a given configuiration, you can't modify that configuration, even if you stop it.

        Other run statuses that allow you to run this command include FAILED and CREATED. A provisioning state that allows you to run this command is FAILED\_PROVISION.
    flag:
        cli-input-json: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        cli-input-yaml: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        compute-config: Configuration parameters for provisioning an DMS Serverless replication.
        generate-cli-skeleton: |-
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values. It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        replication-config-arn: The Amazon Resource Name of the replication to modify.
        replication-config-identifier: The new replication config to apply to the replication.
        replication-settings: The settings for the replication.
        replication-type: The type of replication.
        source-endpoint-arn: The Amazon Resource Name (ARN) of the source endpoint for this DMS serverless replication configuration.
        supplemental-settings: Additional settings for the replication.
        table-mappings: Table mappings specified in the replication.
        target-endpoint-arn: The Amazon Resource Name (ARN) of the target endpoint for this DMS serverless replication configuration.
