name: list-recording-configurations
description: Gets summary information about all recording configurations in your account, in the Amazon Web Services region where the API request is processed.
flags:
    --max-results=: Maximum number of recording configurations to return.
    --next-token=: The first recording configuration to retrieve.
documentation:
    command: Gets summary information about all recording configurations in your account, in the Amazon Web Services region where the API request is processed.
    flag:
        max-results: 'Maximum number of recording configurations to return. Default: your service quota or 100, whichever is smaller.'
        next-token: The first recording configuration to retrieve. This is used for pagination; see the `nextToken` response field.
