name: describe-storage-configuration
description: Retrieves information about the storage configuration for IoT SiteWise.
documentation:
    command: Retrieves information about the storage configuration for IoT SiteWise.
