name: put-account-settings
description: Put the account settings for Artifact.
flags:
    --notification-subscription-status=: Desired notification subscription status.
completion:
    flag:
        notification-subscription-status:
            - SUBSCRIBED
            - NOT_SUBSCRIBED
documentation:
    command: Put the account settings for Artifact.
    flag:
        notification-subscription-status: Desired notification subscription status.
