name: describe-application
description: Returns information about a specific Managed Service for Apache Flink application.
flags:
    --application-name=!: The name of the application.
    --include-additional-details=: Displays verbose information about a Managed Service for Apache Flink application, including the application's job plan.
documentation:
    command: |-
        Returns information about a specific Managed Service for Apache Flink application.

        If you want to retrieve a list of all applications in your account, use the [ListApplications]() operation.
    flag:
        application-name: The name of the application.
        include-additional-details: Displays verbose information about a Managed Service for Apache Flink application, including the application's job plan.
