name: update-media-insights-pipeline-configuration
description: Updates the media insights pipeline's configuration settings.
flags:
    --cli-input-json=: Read arguments from the JSON string provided.
    --cli-input-yaml=: Read arguments from the YAML string provided.
    --elements=!:
        description: The elements in the request, such as a processor for Amazon Transcribe or a sink for a Kinesis Data Stream..
        nargs: -1
    --generate-cli-skeleton: Prints a JSON skeleton to standard output without sending an API request.
    --identifier=!: The unique identifier for the resource to be updated.
    --real-time-alert-configuration=: The configuration settings for real-time alerts for the media insights pipeline.
    --resource-access-role-arn=!: The ARN of the role used by the service to access Amazon Web Services resources.
documentation:
    command: Updates the media insights pipeline's configuration settings.
    flag:
        cli-input-json: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        cli-input-yaml: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        elements: The elements in the request, such as a processor for Amazon Transcribe or a sink for a Kinesis Data Stream..
        generate-cli-skeleton: |-
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values. It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        identifier: The unique identifier for the resource to be updated. Valid values include the name and ARN of the media insights pipeline configuration.
        real-time-alert-configuration: The configuration settings for real-time alerts for the media insights pipeline.
        resource-access-role-arn: The ARN of the role used by the service to access Amazon Web Services resources.
