name: batch-associate-code-security-scan-configuration
description: Associates multiple code repositories with an Amazon Inspector code security scan configuration.
flags:
    --associate-configuration-requests=!: A list of code repositories to associate with the specified scan configuration.
documentation:
    command: Associates multiple code repositories with an Amazon Inspector code security scan configuration.
    flag:
        associate-configuration-requests: A list of code repositories to associate with the specified scan configuration.
