name: get-environment-account-connection
description: In an environment account, get the detailed data for an environment account connection.
flags:
    --id=!: The ID of the environment account connection that you want to get the detailed data for.
documentation:
    command: |-
        In an environment account, get the detailed data for an environment account connection.

        For more information, see [Environment account connections](https://docs.aws.amazon.com/proton/latest/userguide/ag-env-account-connections.html) in the *Proton User guide*.
    flag:
        id: The ID of the environment account connection that you want to get the detailed data for.
