name: delete-application
description: Deletes an application.
flags:
    --application-id=!: The ID of the application that will be deleted.
    --cli-input-json=: Read arguments from the JSON string provided.
    --cli-input-yaml=: Read arguments from the YAML string provided.
    --generate-cli-skeleton: Prints a JSON skeleton to standard output without sending an API request.
documentation:
    command: Deletes an application. An application has to be in a stopped or created state in order to be deleted.
    flag:
        application-id: The ID of the application that will be deleted.
        cli-input-json: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        cli-input-yaml: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        generate-cli-skeleton: |-
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values. It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
