name: modify-redshift-idc-application
description: Changes an existing Amazon Redshift IAM Identity Center application.
flags:
    --authorized-token-issuer-list=: The authorized token issuer list for the Amazon Redshift IAM Identity Center application to change.
    --iam-role-arn=: The IAM role ARN associated with the Amazon Redshift IAM Identity Center application to change.
    --idc-display-name=: The display name for the Amazon Redshift IAM Identity Center application to change.
    --identity-namespace=: The namespace for the Amazon Redshift IAM Identity Center application to change.
    --redshift-idc-application-arn=!: The ARN for the Redshift application that integrates with IAM Identity Center.
    --service-integrations=: A collection of service integrations associated with the application.
documentation:
    command: Changes an existing Amazon Redshift IAM Identity Center application.
    flag:
        authorized-token-issuer-list: The authorized token issuer list for the Amazon Redshift IAM Identity Center application to change.
        iam-role-arn: The IAM role ARN associated with the Amazon Redshift IAM Identity Center application to change. It has the required permissions to be assumed and invoke the IDC Identity Center API.
        idc-display-name: The display name for the Amazon Redshift IAM Identity Center application to change. It appears on the console.
        identity-namespace: The namespace for the Amazon Redshift IAM Identity Center application to change. It determines which managed application verifies the connection token.
        redshift-idc-application-arn: The ARN for the Redshift application that integrates with IAM Identity Center.
        service-integrations: A collection of service integrations associated with the application.
