name: create-configuration-manager
description: Creates a Quick Setup configuration manager resource.
flags:
    --configuration-definitions=!: The definition of the Quick Setup configuration that the configuration manager deploys.
    --description=: A description of the configuration manager.
    --name=: A name for the configuration manager.
    --tags=: Key-value pairs of metadata to assign to the configuration manager.
documentation:
    command: Creates a Quick Setup configuration manager resource. This object is a collection of desired state configurations for multiple configuration definitions and summaries describing the deployments of those definitions.
    flag:
        configuration-definitions: The definition of the Quick Setup configuration that the configuration manager deploys.
        description: A description of the configuration manager.
        name: A name for the configuration manager.
        tags: Key-value pairs of metadata to assign to the configuration manager.
