name: delete-application
description: Deletes an application.
flags:
    --application-id=!: The ID of the application that will be deleted.
documentation:
    command: Deletes an application. An application has to be in a stopped or created state in order to be deleted.
    flag:
        application-id: The ID of the application that will be deleted.
