name: create-application
description: Creates an application that has one configuration template named `default` and no application versions.
flags:
    --application-name=!: The name of the application.
    --description=: Your description of the application.
    --resource-lifecycle-config=: Specifies an application resource lifecycle configuration to prevent your application from accumulating too many versions.
    --tags=: Specifies the tags applied to the application.
documentation:
    command: Creates an application that has one configuration template named `default` and no application versions.
    flag:
        application-name: The name of the application. Must be unique within your account.
        description: Your description of the application.
        resource-lifecycle-config: Specifies an application resource lifecycle configuration to prevent your application from accumulating too many versions.
        tags: |-
            Specifies the tags applied to the application.

            Elastic Beanstalk applies these tags only to the application. Environments that you create in the application don't inherit the tags.
