name: delete-home-region-control
description: This operation deletes the home region configuration for the calling account.
flags:
    --control-id=!: A unique identifier that's generated for each home region control.
documentation:
    command: This operation deletes the home region configuration for the calling account. The operation does not delete discovery or migration tracking data in the home region.
    flag:
        control-id: A unique identifier that's generated for each home region control. It's always a string that begins with "hrc-" followed by 12 lowercase letters and numbers.
