name: put-voice-connector-external-systems-configuration
description: Adds an external systems configuration to a Voice Connector.
flags:
    --contact-center-system-types=: The contact center system to use.
    --session-border-controller-types=: The session border controllers to use.
    --voice-connector-id=!: The ID of the Voice Connector for which to add the external system configuration.
documentation:
    command: Adds an external systems configuration to a Voice Connector.
    flag:
        contact-center-system-types: The contact center system to use.
        session-border-controller-types: The session border controllers to use.
        voice-connector-id: The ID of the Voice Connector for which to add the external system configuration.
