name: list-studio-lifecycle-configs
description: Lists the Amazon SageMaker AI Studio Lifecycle Configurations in your Amazon Web Services Account.
flags:
    --app-type-equals=: A parameter to search for the App Type to which the Lifecycle Configuration is attached.
    --creation-time-after=: A filter that returns only Lifecycle Configurations created on or after the specified time.
    --creation-time-before=: A filter that returns only Lifecycle Configurations created on or before the specified time.
    --max-results=: The total number of items to return in the response.
    --modified-time-after=: A filter that returns only Lifecycle Configurations modified after the specified time.
    --modified-time-before=: A filter that returns only Lifecycle Configurations modified before the specified time.
    --name-contains=: A string in the Lifecycle Configuration name.
    --next-token=: If the previous call to ListStudioLifecycleConfigs didn't return the full set of Lifecycle Configurations, the call returns a token for getting the next set of Lifecycle Configurations.
    --sort-by=: The property used to sort results.
    --sort-order=: The sort order.
completion:
    flag:
        app-type-equals:
            - JupyterServer
            - KernelGateway
            - CodeEditor
            - JupyterLab
        sort-by:
            - CreationTime
            - LastModifiedTime
            - Name
        sort-order:
            - Ascending
            - Descending
documentation:
    command: Lists the Amazon SageMaker AI Studio Lifecycle Configurations in your Amazon Web Services Account.
    flag:
        app-type-equals: A parameter to search for the App Type to which the Lifecycle Configuration is attached.
        creation-time-after: A filter that returns only Lifecycle Configurations created on or after the specified time.
        creation-time-before: A filter that returns only Lifecycle Configurations created on or before the specified time.
        max-results: The total number of items to return in the response. If the total number of items available is more than the value specified, a `NextToken` is provided in the response. To resume pagination, provide the `NextToken` value in the as part of a subsequent call. The default value is 10.
        modified-time-after: A filter that returns only Lifecycle Configurations modified after the specified time.
        modified-time-before: A filter that returns only Lifecycle Configurations modified before the specified time.
        name-contains: A string in the Lifecycle Configuration name. This filter returns only Lifecycle Configurations whose name contains the specified string.
        next-token: If the previous call to ListStudioLifecycleConfigs didn't return the full set of Lifecycle Configurations, the call returns a token for getting the next set of Lifecycle Configurations.
        sort-by: The property used to sort results. The default value is CreationTime.
        sort-order: The sort order. The default value is Descending.
