name: delete-configuration-set
description: Deletes an existing configuration set.
flags:
    --cli-input-json=: Read arguments from the JSON string provided.
    --cli-input-yaml=: Read arguments from the YAML string provided.
    --configuration-set-name=!: The name of the configuration set or the configuration set ARN that you want to delete.
    --generate-cli-skeleton: Prints a JSON skeleton to standard output without sending an API request.
documentation:
    command: |-
        Deletes an existing configuration set.

        A configuration set is a set of rules that you apply to voice and SMS messages that you send. In a configuration set, you can specify a destination for specific types of events related to voice and SMS messages.
    flag:
        cli-input-json: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        cli-input-yaml: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        configuration-set-name: The name of the configuration set or the configuration set ARN that you want to delete. The ConfigurationSetName and ConfigurationSetArn can be found using the [DescribeConfigurationSets]() action.
        generate-cli-skeleton: |-
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values. It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
