name: configure-logs-for-playback-configuration
description: Defines where AWS Elemental MediaTailor sends logs for the playback configuration.
flags:
    --ads-interaction-log=: The event types that MediaTailor emits in logs for interactions with the ADS.
    --cli-input-json=: Read arguments from the JSON string provided.
    --cli-input-yaml=: Read arguments from the YAML string provided.
    --enabled-logging-strategies=:
        description: The method used for collecting logs from AWS Elemental MediaTailor.
        nargs: -1
    --generate-cli-skeleton: Prints a JSON skeleton to standard output without sending an API request.
    --manifest-service-interaction-log=: The event types that MediaTailor emits in logs for interactions with the origin server.
    --percent-enabled=!: The percentage of session logs that MediaTailor sends to your CloudWatch Logs account.
    --playback-configuration-name=!: The name of the playback configuration.
documentation:
    command: Defines where AWS Elemental MediaTailor sends logs for the playback configuration.
    flag:
        ads-interaction-log: The event types that MediaTailor emits in logs for interactions with the ADS.
        cli-input-json: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        cli-input-yaml: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        enabled-logging-strategies: |-
            The method used for collecting logs from AWS Elemental MediaTailor. To configure MediaTailor to send logs directly to Amazon CloudWatch Logs, choose `LEGACY_CLOUDWATCH`. To configure MediaTailor to send logs to CloudWatch, which then vends the logs to your destination of choice, choose `VENDED_LOGS`. Supported destinations are CloudWatch Logs log group, Amazon S3 bucket, and Amazon Data Firehose stream.

            To use vended logs, you must configure the delivery destination in Amazon CloudWatch, as described in [Enable logging from AWS services, Logging that requires additional permissions \[V2\]](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html#AWS-vended-logs-permissions-V2).
        generate-cli-skeleton: |-
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values. It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        manifest-service-interaction-log: The event types that MediaTailor emits in logs for interactions with the origin server.
        percent-enabled: |-
            The percentage of session logs that MediaTailor sends to your CloudWatch Logs account. For example, if your playback configuration has 1000 sessions and percentEnabled is set to `60`, MediaTailor sends logs for 600 of the sessions to CloudWatch Logs. MediaTailor decides at random which of the playback configuration sessions to send logs for. If you want to view logs for a specific session, you can use the [debug log mode](https://docs.aws.amazon.com/mediatailor/latest/ug/debug-log-mode.html).

            Valid values: `0` - `100`
        playback-configuration-name: The name of the playback configuration.
