name: list-environment-hosts
description: List the hosts within an environment.
flags:
    --environment-id=!: A unique ID for the environment.
    --max-results=: The maximum number of results to return.
    --next-token=: A unique pagination token for each page.
documentation:
    command: List the hosts within an environment.
    flag:
        environment-id: A unique ID for the environment.
        max-results: The maximum number of results to return. If you specify `MaxResults` in the request, the response includes information up to the limit specified.
        next-token: A unique pagination token for each page. If `nextToken` is returned, there are more results available. Make the call again using the returned token with all other arguments unchanged to retrieve the next page. Each pagination token expires after 24 hours. Using an expired pagination token will return an *HTTP 400 InvalidToken* error.
