name: import-application-usage
description: Ingests application usage data from Amazon Simple Storage Service (Amazon S3).
flags:
    --source-s3-location=!: Amazon S3 location to import application usage data from.
documentation:
    command: |-
        Ingests application usage data from Amazon Simple Storage Service (Amazon S3).

        The data must already exist in the S3 location. As part of the action, AWS Application Cost Profiler copies the object from your S3 bucket to an S3 bucket owned by Amazon for processing asynchronously.
    flag:
        source-s3-location: Amazon S3 location to import application usage data from.
