name: get-application
description: Gets the specified application.
flags:
    --application-id=!: The Amazon Resource Name (ARN) of the application.
    --semantic-version=: The semantic version of the application to get.
documentation:
    command: Gets the specified application.
    flag:
        application-id: The Amazon Resource Name (ARN) of the application.
        semantic-version: The semantic version of the application to get.
