name: delete-column-statistics-task-settings
description: Deletes settings for a column statistics task.
flags:
    --database-name=!: The name of the database where the table resides.
    --table-name=!: The name of the table for which to delete column statistics.
documentation:
    command: Deletes settings for a column statistics task.
    flag:
        database-name: The name of the database where the table resides.
        table-name: The name of the table for which to delete column statistics.
