name: list-environment-templates
description: List environment templates.
flags:
    --max-results=: The maximum number of environment templates to list.
    --next-token=: A token that indicates the location of the next environment template in the array of environment templates, after the list of environment templates that was previously requested.
documentation:
    command: List environment templates.
    flag:
        max-results: The maximum number of environment templates to list.
        next-token: A token that indicates the location of the next environment template in the array of environment templates, after the list of environment templates that was previously requested.
