name: create-configured-table-association-analysis-rule
description: Creates a new analysis rule for an associated configured table.
flags:
    --analysis-rule-policy=!: The analysis rule policy that was created for the configured table association.
    --analysis-rule-type=!: The type of analysis rule.
    --configured-table-association-identifier=!: The unique ID for the configured table association.
    --membership-identifier=!: A unique identifier for the membership that the configured table association belongs to.
completion:
    flag:
        analysis-rule-type:
            - AGGREGATION
            - LIST
            - CUSTOM
documentation:
    command: Creates a new analysis rule for an associated configured table.
    flag:
        analysis-rule-policy: The analysis rule policy that was created for the configured table association.
        analysis-rule-type: The type of analysis rule.
        configured-table-association-identifier: The unique ID for the configured table association. Currently accepts the configured table association ID.
        membership-identifier: A unique identifier for the membership that the configured table association belongs to. Currently accepts the membership ID.
