name: describe-ldapssettings
description: Describes the status of LDAP security for the specified directory.
flags:
    --directory-id=!: The identifier of the directory.
    --limit=: Specifies the number of items that should be displayed on one page.
    --next-token=: The type of next token used for pagination.
    --type=: The type of LDAP security to enable.
completion:
    flag:
        type:
            - Client
documentation:
    command: Describes the status of LDAP security for the specified directory.
    flag:
        directory-id: The identifier of the directory.
        limit: Specifies the number of items that should be displayed on one page.
        next-token: The type of next token used for pagination.
        type: The type of LDAP security to enable. Currently only the value `Client` is supported.
