name: list-clusters
description: Returns an array of all the clusters in an account.
flags:
    --max-results=: The number of objects that you want to return with this call.
    --next-token=: The token that identifies which batch of results you want to see.
documentation:
    command: Returns an array of all the clusters in an account.
    flag:
        max-results: The number of objects that you want to return with this call.
        next-token: The token that identifies which batch of results you want to see.
