name: list-deployments
description: Lists the deployments for an environment in descending deployment number order.
flags:
    --application-id=!: The application ID.
    --environment-id=!: The environment ID.
    --max-results=: The maximum number of items that may be returned for this call.
    --next-token=: The token returned by a prior call to this operation indicating the next set of results to be returned.
documentation:
    command: Lists the deployments for an environment in descending deployment number order.
    flag:
        application-id: The application ID.
        environment-id: The environment ID.
        max-results: The maximum number of items that may be returned for this call. If there are items that have not yet been returned, the response will include a non-null `NextToken` that you can provide in a subsequent call to get the next set of results.
        next-token: The token returned by a prior call to this operation indicating the next set of results to be returned. If not specified, the operation will return the first set of results.
