name: batch-get-application-revisions
description: Gets information about one or more application revisions.
flags:
    --application-name=!: The name of an CodeDeploy application about which to get revision information.
    --revisions=!: An array of `RevisionLocation` objects that specify information to get about the application revisions, including type and location.
documentation:
    command: Gets information about one or more application revisions. The maximum number of application revisions that can be returned is 25.
    flag:
        application-name: The name of an CodeDeploy application about which to get revision information.
        revisions: An array of `RevisionLocation` objects that specify information to get about the application revisions, including type and location. The maximum number of `RevisionLocation` objects you can specify is 25.
