name: update-continuous-deployment-policy
description: Updates a continuous deployment policy.
flags:
    --cli-input-json=: Read arguments from the JSON string provided.
    --cli-input-yaml=: Read arguments from the YAML string provided.
    --continuous-deployment-policy-config=!: The continuous deployment policy configuration.
    --generate-cli-skeleton: Prints a JSON skeleton to standard output without sending an API request.
    --id=!: The identifier of the continuous deployment policy that you are updating.
    --if-match=: The current version (`ETag` value) of the continuous deployment policy that you are updating.
documentation:
    command: |-
        Updates a continuous deployment policy. You can update a continuous deployment policy to enable or disable it, to change the percentage of traffic that it sends to the staging distribution, or to change the staging distribution that it sends traffic to.

        When you update a continuous deployment policy configuration, all the fields are updated with the values that are provided in the request. You cannot update some fields independent of others. To update a continuous deployment policy configuration:

        1. Use `GetContinuousDeploymentPolicyConfig` to get the current configuration.
        2. Locally modify the fields in the continuous deployment policy configuration that you want to update.
        3. Use `UpdateContinuousDeploymentPolicy`, providing the entire continuous deployment policy configuration, including the fields that you modified and those that you didn't.
    flag:
        cli-input-json: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        cli-input-yaml: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        continuous-deployment-policy-config: The continuous deployment policy configuration.
        generate-cli-skeleton: |-
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values. It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        id: The identifier of the continuous deployment policy that you are updating.
        if-match: The current version (`ETag` value) of the continuous deployment policy that you are updating.
