name: create-configuration-manager
description: Creates a Quick Setup configuration manager resource.
flags:
    --cli-input-json=: Read arguments from the JSON string provided.
    --cli-input-yaml=: Read arguments from the YAML string provided.
    --configuration-definitions=!: The definition of the Quick Setup configuration that the configuration manager deploys.
    --description=: A description of the configuration manager.
    --generate-cli-skeleton: Prints a JSON skeleton to standard output without sending an API request.
    --name=: A name for the configuration manager.
    --tags=: Key-value pairs of metadata to assign to the configuration manager.
documentation:
    command: Creates a Quick Setup configuration manager resource. This object is a collection of desired state configurations for multiple configuration definitions and summaries describing the deployments of those definitions.
    flag:
        cli-input-json: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        cli-input-yaml: |-
            Reads arguments from the JSON string provided.
            The JSON string follows the  format  provided  by --generate-cli-skeleton.
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values.
            It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        configuration-definitions: The definition of the Quick Setup configuration that the configuration manager deploys.
        description: A description of the configuration manager.
        generate-cli-skeleton: |-
            If other arguments are provided on the command line,  those  values  will override the JSON-provided values. It is not possible to pass arbitrary binary values using a JSON-provided value as the string will be taken literally.
            This may  not  be  specified  along with --cli-input-yaml.
        name: A name for the configuration manager.
        tags: Key-value pairs of metadata to assign to the configuration manager.
