name: describe-protect-configurations
description: Retrieves the protect configurations that match any of filters.
flags:
    --filters=: An array of ProtectConfigurationFilter objects to filter the results.
    --max-results=: The maximum number of results to return per each request.
    --next-token=: The token to be used for the next set of paginated results.
    --protect-configuration-ids=: An array of protect configuration identifiers to search for.
documentation:
    command: Retrieves the protect configurations that match any of filters. If a filter isn’t provided then all protect configurations are returned.
    flag:
        filters: An array of ProtectConfigurationFilter objects to filter the results.
        max-results: The maximum number of results to return per each request.
        next-token: The token to be used for the next set of paginated results. You don't need to supply a value for this field in the initial request.
        protect-configuration-ids: An array of protect configuration identifiers to search for.
