name: disassociate-workspace-application
description: Disassociates the specified application from a WorkSpace.
flags:
    --application-id=!: The identifier of the application.
    --workspace-id=!: The identifier of the WorkSpace.
documentation:
    command: Disassociates the specified application from a WorkSpace.
    flag:
        application-id: The identifier of the application.
        workspace-id: The identifier of the WorkSpace.
