name: authorize-cache-security-group-ingress
description: Allows network ingress to a cache security group.
flags:
    --cache-security-group-name=!: The cache security group that allows network ingress.
    --ec2-security-group-name=!: The Amazon EC2 security group to be authorized for ingress to the cache security group.
    --ec2-security-group-owner-id=!: The Amazon account number of the Amazon EC2 security group owner.
documentation:
    command: |-
        Allows network ingress to a cache security group. Applications using ElastiCache must be running on Amazon EC2, and Amazon EC2 security groups are used as the authorization mechanism.

        You cannot authorize ingress from an Amazon EC2 security group in one region to an ElastiCache cluster in another region.
    flag:
        cache-security-group-name: The cache security group that allows network ingress.
        ec2-security-group-name: The Amazon EC2 security group to be authorized for ingress to the cache security group.
        ec2-security-group-owner-id: The Amazon account number of the Amazon EC2 security group owner. Note that this is not the same thing as an Amazon access key ID - you must provide a valid Amazon account number for this parameter.
