name: describe-security-configuration
description: Provides the details of a security configuration by returning the configuration JSON.
flags:
    --name=!: The name of the security configuration.
documentation:
    command: Provides the details of a security configuration by returning the configuration JSON.
    flag:
        name: The name of the security configuration.
