# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Print database connection information. Useful when configuring GUI clients.
flags:
    --db&=: Print information for the specified database.
    -f, --format=: 'Print format: "text" to print in table format (default), "cmd" to print connect command, "json" or "yaml" to print in JSON or YAML.'
documentation:
    command: '[AI] The `tsh db config` command is used in Tenable''s SecurityCenter Continuous View (CV) platform with the Tenable Data Bridge (tsh) tool. This command is utilized for configuring the connection settings between tsh and a database, typically Nessus or other Tenable products, to enable data transfer and integration between them. It sets up parameters like database type, hostname or IP address, port number, username, password, and authentication method.'
    flag:
        db: '[AI] The command `tsh db config --db` is for the TSH (Tenable Security Hardening) tool, specifically used to configure the database settings. The "--db" option indicates that the configuration will be related to the database. This command allows you to set various database parameters such as the database name, username, password, host, and port. It ensures that the TSH tool is able to connect and communicate with the database effectively.'
        format: |-
            [AI] `tsh` is a TupleScope shell, a command-line interface for Apache Superset data exploration tool. The command `tsh db config --format` is used to retrieve the database configuration information in a specific format.

            The `--format` option allows specifying the desired output format which can be:

            * 'json': returns JSON formatted data
            * 'csv': returns comma-separated value data
            * 'table': returns tabular data with headers

            For example, to get the database configuration in JSON format, use `tsh db config --format json`. This command will return a JSON object containing various database connection properties such as host, port, user, password, and database name.
