# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: puttyconfig
description: Add PuTTY saved session configuration for specified hostname to Windows registry
hidden: true
flags:
    --leaf=: Add a configuration for connecting to a leaf cluster
    -p, --port=: SSH port on a remote host
documentation:
    command: |-
        [AI] The `tsh puttyconfig` command is not a standard Linux or Unix command, as it appears to be specific to the Turbochef Supervisor (Tsh) software used in industrial automation environments. This command is likely used to configure PuTTY settings within the Tsh environment for managing SSH connections to remote devices.

        For instance, when using Tsh to manage Putty sessions, you might use this command followed by a specific configuration name or ID, such as `tsh puttyconfig my_session`, to apply or modify PuTTY configuration settings associated with that session in the Tsh system. The actual changes made depend on the specific options defined within your PuTTY configuration file for that session. Consult the Turbochef Supervisor documentation for more details on using this command.
    flag:
        leaf: '[AI] `tsh` is a Tcl-based Secure Shell (SSH) client for Windows, and `puttyconfig` is its configuration file. The command `tsh puttyconfig --leaf` returns the raw, flat key-value pairs of the configuration file without any nested or grouped structure. In other words, it shows only the top-level keys and their values in the configuration file.'
        port: '[AI] The command `tsh puttyconfig --port` is used with the TerraTerm SSH (TSH) application and PuTTY configuration files. It modifies the specified port number in a PuTTY configuration file. For example, `--port 22` sets the port number to 22. This command allows users to customize their SSH connections by adjusting the port used for each connection.'
