# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Print OpenSSH configuration details.
documentation:
    command: '[AI] The `tsh config` command is used in Tsung, a open-source load testing tool, to configure various settings and options for Tsung scripts. It allows users to define global parameters, define new resources or modify existing ones, and set up logging and reporting features. These configurations are saved in an XML file, which can be used to customize the behavior of Tsung during load testing simulations.'
