# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config [flags]
aliases:
    - conf
description: Set and get glab settings
flags:
    -g, --global: Use global config file
documentation:
    command: '[AI] `glab config` is a GitLab CLI (Command Line Interface) command used to manage GitLab-specific configuration settings. It allows users to view, edit, or set various configuration options related to GitLab and its integrations with other tools. The configurations can include things like personal access tokens, default branches for merging, or the URL of a GitLab instance.'
    flag:
        global: '[AI] `glab` is a Git interface tool that provides additional features for interacting with Git repositories. The command `glab config --global` is used to configure global settings for `glab`. The `--global` option sets the configuration options to be applied system-wide across all projects, rather than being limited to a specific repository. For instance, you can set your preferred text editor or default branch with this command. It modifies the user''s Git configuration file (usually located in `~/.config/glab/config`) to include these settings.'
