# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: cp
description: Copy config to another stack
persistentflags:
    --path: The key contains a path to a property in a map or list to set
    -d, --dest=: The name of the new stack to copy the config to
documentation:
    command: '[AI] `pulumi config cp` is a command in Pulumi, an infrastructure as code platform, used to copy configuration values between stacks or projects. It allows you to synchronize configuration settings between different instances of your Pulumi applications while preserving any local overrides. This can be helpful when managing multiple environments with similar but not identical configurations. The syntax is `pulumi config cp <src> <dest>:<path>`, where `<src>` specifies the source stack or project, and `<dest>` is the destination location, along with an optional `:<path>` to copy a specific configuration path.'
