# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get
description: Get a single configuration value
flags:
    -j, --json: Emit output as JSON
persistentflags:
    --path: The key contains a path to a property in a map or list to get
documentation:
    command: '[AI] `pulumi config get` is a command used in Pulumi, an infrastructure as code (IaC) tool, to retrieve the value of a specific configuration variable from your project''s configuration file or environment variables. The command takes one argument: the name of the configuration variable to be fetched. It outputs the corresponding value to help you understand the current setting for that particular configuration.'
    flag:
        json: '[AI] `pulumi config get --json` is a command used in Pulumi, an infrastructure as code platform, to retrieve the current value of a configuration variable in its raw JSON format. This command is typically used when interacting with Pulumi programmatically or when needing to pass the configuration data to other scripts or tools. It returns the value of the specified configuration key as a JSON string.'
