# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: refresh
description: Update the local configuration based on the most recent deployment of the stack
persistentflags:
    -f, --force: Overwrite configuration file, if it exists, without creating a backup
documentation:
    command: '[AI] `pulumi config refresh` is a command used in Pulumi, an infrastructure as code platform, to update the local configuration values with the latest settings from the remote backend or stack. This ensures that your local environment remains in sync with the cloud environment, reducing the risk of misconfigurations and inconsistencies between the two.'
