# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm
description: Remove configuration value
persistentflags:
    --path: The key contains a path to a property in a map or list to remove
documentation:
    command: '[AI] `pulumi config rm` is a command used in Pulumi, an infrastructure as code platform. It is used to remove a specific configuration variable from your project''s Pulumi.yaml file or the environment variables used by Pulumi. By providing the name of the configuration variable as an argument, this command helps in maintaining a clean and focused configuration setup for your infrastructure deployments.'
