# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: rm-all
description: Remove multiple configuration values
persistentflags:
    --path: Parse the keys as paths in a map or list rather than raw strings
documentation:
    command: '[AI] `pulumi config rm-all` is a command used in Pulumi, an infrastructure as code platform, to remove all existing configuration values set for a project or a specific resource. This command helps to reset configuration settings to their default values and start with a clean slate while working on a new deployment or configuration change. It does not affect the actual infrastructure managed by Pulumi until you apply the updated configuration using `pulumi up`.'
