# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set
description: Set configuration value
persistentflags:
    --path: The key contains a path to a property in a map or list to set
    --plaintext: Save the value as plaintext (unencrypted)
    --secret: Encrypt the value instead of storing it in plaintext
documentation:
    command: '[AI] `pulumi config set` is a command used in Pulumi, an infrastructure as code platform, to update the local configuration file with new values. It sets or modifies specific key-value pairs in the config file and persists the changes for the current directory. This allows adjusting settings without changing the code, making it useful for managing sensitive information like access keys or environment-specific variables.'
