# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: set-all
description: Set multiple configuration values
persistentflags:
    --path: Parse the keys as paths in a map or list rather than raw strings
    --plaintext*=: Marks a value as plaintext (unencrypted)
    --secret*=: Marks a value as secret to be encrypted
documentation:
    command: '[AI] `pulumi config set-all` is a command used in Pulumi, an infrastructure as code platform, to set all configurable settings for a specific project or stack to their default values. This command can be useful when starting a new project or when you want to reset the configuration to its initial state. It overwrites any existing configurations without asking for confirmation.'
