# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: gpg-sign
description: Sign a given piece of metadata usign GPG
flags:
    -h, --help: show this help message and exit
documentation:
    command: '[AI] The `conda-content-trust gpg-sign` command is used to sign Anaconda/Conda content metadata files with a GPG key for added security in Conda environments. By signing the metadata files, users can verify their authenticity and integrity when adding or updating packages using the Conda package manager. The process involves importing the trusted key into the Conda environment, setting up the trust settings, and then using the `gpg-sign` command to sign the metadata files located in the Conda channels.'
    flag:
        help: |-
            [AI] The `conda-content-trust gpg-sign` command is a utility within Anaconda Distribution for managing GPG (Gnu Privacy Guard) signatures used in Conda's content trust system. This system ensures the authenticity and integrity of packages and channels in Conda environments.

            The `--help` flag provides a brief explanation of the available options when using this command:

            - `gpg-sign <filename>|<keyid> ...`: Sign one or more package files with your GPG key, creating new signatures or updating existing ones. The `<filename>` argument is the path to the Conda package file and the `<keyid>` is the identifier of your GPG signing key.
            - `--detach-sign <filename>`: Detach an existing signature from a package file, making it no longer trusted by Conda.
            - `--trust <filename>|<keyid> [<level>:<level>...]`: Trust the given GPG key(s) for specific levels (e.g., 'r', 'rw', 'h') or all levels. This sets up the trust settings in the Conda environment's `trusted_channels.yml` file.
            - `--list <keyid> [<level>:<level>...]`: List the current trust status and level(s) for the specified GPG key.
            - `--verify <filename>|<url>`: Verify the authenticity of a package file or URL using existing signatures in your Conda environment.
            - `--force`: Force signing a file without confirmation prompts or overwriting existing signatures. Use this option with caution, as it may compromise security.
            - `--gpg-dir <path>`: Specify the custom GPG directory path for storing keys and trustdb files. By default, Anaconda will use its own internal directories.
            - `--help|-h|--version|-V`: Display help information or version details about this command.
