# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: conda-content-trust
description: Signing and verification tools for Conda
flags:
    -V, --version: Show the conda-content-trust version number and exit.
    -h, --help: show this help message and exit
documentation:
    command: '[AI] "conda-content-trust" is a utility in Anaconda Distribution (Conda) that helps manage the certificate revocation lists (CRLs and OCSP) for Conda''s packages signature verification. It ensures the trustworthiness of packages by checking their digital signatures against these revocation lists to prevent using outdated or compromised certificates, ensuring secure package installations.'
    flag:
        help: |-
            [AI] `conda-content-trust` is a utility in Anaconda distribution for managing content trust with conda environments. The `--help` option provides a summary of its command line interface and available options:

            ```bash
            usage: conda-content-trust [-h] [--version] {add,remove,list,sign,verify,authenticity} ...

            Manage content trust in Anaconda distributions using conda environments.

            options:
              -h, --help            Show this help message and exit.
              --version             Show program's version number and exit.
              {add,remove,list,sign,verify,authenticity}
                add                 Add a new trusted channel or package key to the cache.
                remove              Remove a trusted channel or package key from the cache.
                list                List all trusted channels and keys in the cache.
                sign                Sign a local conda package with a private key.
                verify              Verify the authenticity of a local or remote package.
                authenticity        Display the authentication status of a specific channel or package.
            ```

            Each command (add, remove, list, sign, verify, and authenticity) manages various aspects of content trust within conda environments.
        version: '[AI] `conda-content-trust` is a utility in Anaconda Distribution for managing package signatures and verifying the authenticity of conda packages. The command `conda-content-trust --version` is used to check the version of this utility installed within your conda environment. It displays the version number along with some additional information such as the build date, commit hash, and operating system. This information helps users ensure they have the latest and secure version of the content trust utility.'
