# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: gpg-key-lookup
description: Fetch the actual ed25519 public key value of the underlying key
flags:
    -h, --help: show this help message and exit
documentation:
    command: '[AI] The `conda-content-trust gpg-key-lookup` command is used in Anaconda distribution''s environment management system (Conda) to search for and display the GPG keys associated with specific Conda channels or packages. This command helps users verify the authenticity of the packages they install by checking if the keys match those stored in the Anaconda repository. It does not add, modify or delete any keys; it simply looks them up.'
    flag:
        help: |-
            [AI] The `conda-content-trust gpg-key-lookup` command is a utility within Anaconda's Conda package manager. It is used to search for and display the public GPG keys associated with specific Conda channels or repositories. This command helps ensure the authenticity of packages installed via Conda by allowing users to verify that the keys belong to trusted sources.

            Usage: `conda-content-trust gpg-key-lookup [options] [--key <key_id>|--url <repo_url>]`

            Options:

            1. `--key <key_id>`: Look up the key associated with a given key ID.
            2. `--url <repo_url>`: Look up the keys associated with a specific Conda repository URL.
            3. `--output <file>`: Write output to a file instead of standard output.
            4. `--quiet`: Suppress verbose output.
            5. `--help`: Display help information for the command.
