# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Change configuration options, such as sending of optional analytics data
flags:
    -h, --help: help for config
documentation:
    command: '[AI] `gh-copilot config` is a command used in GitHub''s Copilot, an AI pair programming companion. It allows you to configure various settings for the Copilot extension in your code editor. You can use it to enable or disable features, set language preferences, and customize other aspects of the Copilot experience. For example, `gh-copilot config --enable-suggestions true` would enable suggestions from Copilot. Consult the Copilot documentation for more information on available configuration options.'
    flag:
        help: '[AI] `gh-copilot config --help` is a command used in GitHub''s Copilot extension for various code editors. This command displays help information about configuring Copilot, including available options and their descriptions. Users can run it to understand how to set up the environment variables, authentication token, and other configuration details required for Copilot to function effectively.'
