# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Application configuration management
documentation:
    command: '[AI] The "waypoint config" command is used in navigation systems, particularly in autonomous vehicle and drone technologies, to configure or modify waypoints in a mission plan. Waypoints represent specific geographic locations that the vehicle or drone is programmed to reach. By using this command, users can change the sequence, location, or other attributes of the waypoints to customize the mission plan according to their needs.'
