# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Configure a conda environment
documentation:
    command: '[AI] `conda-env config` is a command used in Anaconda/Conda environments to modify configuration settings. It allows users to create, edit, and delete specific keys within the environment''s `.yml` or `.json` files that define the environment. For instance, you can use it to set the channel URL for package updates or add custom dependencies. The basic syntax is `conda env config --edit <env_name>`, which opens the configuration file in a text editor, enabling you to make the desired changes.'
