# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: conda-env
description: Manage conda environments
documentation:
    command: |-
        [AI] `conda-env` is a command used with Anaconda and Miniconda distribution of Python for managing and creating isolated environments to install and run specific versions of packages, without interfering with other projects' dependencies. The primary functions include:

        1. Creating new environments: `conda create --name myenv`
        2. Activating an existing environment: `conda activate myenv`
        3. Listing available environments: `conda info --envs`
        4. Exporting/importing environment configurations: `conda env export > myenv.yml` or `conda env import < myenv.yml`
        5. Updating the packages in an active environment: `conda upgrade --all`
        6. Adding or removing specific packages: `conda install package_name` or `conda remove package_name`
