# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: unset
description: Unset environment variables for a conda environment
flags:
    -h, --help: Show this help message and exit.
    -n, --name=: Name of environment
    -p, --prefix=: Full path to environment location
documentation:
    command: '[AI] The `conda-env config vars unset` command is used to remove (unset) environment variable configurations from a Conda environment in Anaconda. This command is typically executed within an activated Conda environment, and it allows you to delete specific variable names without affecting other variables. Unsetting variables does not cause any value modification, just removes the variable definition from the current environment configuration file.'
    flag:
        help: |-
            [AI] `conda-env config vars unset --help` is a command used in Anaconda's Conda environment management system. This command is utilized to unset (remove) configuration variables within the current Conda environment. The `--help` option provides detailed information about how to use this command effectively, including available options and examples.

            Usage:
            ```bash
            conda-env config vars unset [NAME] --help
            ```
            The NAME argument is optional and specifies the name of the configuration variable you want to unset if known. If no variable name is provided, all the environment-specific variables will be unset.
        name: '[AI] The `conda-env config vars unset --name <ENV_NAME>` command is used in Anaconda or Miniconda environments to unset (remove) all configuration variables for the specified environment named `<ENV_NAME>`. This can be helpful when troubleshooting issues, resetting settings, or preparing an environment for a clean installation. It does not affect the packages installed within the environment.'
        prefix: '[AI] The command `conda config vars unset --prefix` is used in Anaconda or Miniconda environments to unset the `prefix` configuration variable. This variable determines the base installation directory for Conda packages. Unsetting it allows Conda to use a default location or to configure it with a different path later, if needed. It doesn''t affect the current environment''s prefix, but sets up a blank slate for creating new environments with custom install directories.'
