# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
description: List environment variables for a conda environment
flags:
    --json: Report all output as json
    -h, --help: Show this help message and exit
    -n, --name=: Name of environment
    -p, --prefix=: Full path to environment location
    -q, --quiet: Do not display progress bar
    -v, --verbose: Use once for info, twice for debug, three times for trace
documentation:
    command: '[AI] The `conda-env config vars list` command is used to list all the user-defined variables in a given Conda environment. This command displays the name and value of each variable set in the current Conda environment configuration file. It helps users to view and manage custom environment variables within their Conda projects.'
    flag:
        help: |-
            [AI] `conda-env config vars list` is a command used in Anaconda or Miniconda environments to display a list of configuration variables and their current values for the active conda environment. The `--help` flag provides information about how to use this specific command, including its syntax and available options. Here's what the help message says:

            ```bash
            Usage: conda-env config vars [<environment>] [--help]

            Options:
              <environment>: The environment name or file path to target, defaults to the active one
              --help: Show this help message and exit.

            Description:
              List configuration variables and their values for a given conda environment. If no environment is specified, it lists the values for the active environment.
            ```

            In summary, `conda-env config vars list --help` displays the usage instructions and options for listing the configuration variables and their values in a specified or the current active conda environment.
        json: '[AI] The `conda-env config vars list --json` command is used in Anaconda or Miniconda environments to retrieve a JSON formatted output of all configuration variables set within the current conda environment. This command provides a comprehensive view of all key-value pairs that define the environment''s configurations, allowing users to understand the settings and potentially modify them for specific use cases.'
        name: |-
            [AI] The `conda-env config vars list --name` command is used in Anaconda or Miniconda environments to display a list of configuration variable names and their current values for the specified environment.

            Here's a brief explanation of its usage:

            1. `conda-env`: It is the name of the Conda Environment Management System utility.
            2. `config`: This option is used to manipulate configuration variables in an Anaconda/Miniconda environment.
            3. `vars`: This option displays a list of all configuration variables.
            4. `list`: This option shows the values for each variable, one per line.
            5. `--name <environment_name>`: This argument specifies the name of the target Anaconda/Miniconda environment.

            So, when you run this command with the specified argument, it will display a list of configuration variables and their respective values for the given environment.
        prefix: '[AI] The `conda-env config vars list --prefix` command is used in Anaconda or Miniconda environments to display a list of configuration variables and their values for the specified Conda environment prefix. This prefix argument specifies the location of the Conda installation, usually represented by the path to the base or envs directory. By executing this command, you can inspect and understand which config vars are set in your given Conda environment, enabling effective management and customization of your environments.'
        quiet: '[AI] The command `conda env config vars list --quiet` is used in Anaconda or Miniconda environments to list all the configuration variables (also known as environment variables) for the current conda environment in a quiet mode. It means that only the variable names and values will be displayed, without any additional information or formatting.'
        verbose: '[AI] The `conda-env config vars list --verbose` command is used in Anaconda or Miniconda environments to display a list of all configuration variables (also known as custom Stochastic Processes with Dependent and Independent Variables (SPDIs) or simply env variables) for the current active environment with detailed information. The `--verbose` option increases the output level, providing more data such as variable names, values, and their sources (local, remote, or default). It helps users understand which variables are set in the environment and where they originated from.'
