# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Print the site configuration
documentation:
    command: '[AI] `hugo config` is a command used with Hugo, a popular static site generator for creating blogs and websites. This command is used to load or modify the configuration file (usually named `config.toml`) for your Hugo project. It allows you to set various site-wide options such as title, description, language, theme, and more. If no argument is provided, it simply loads the current config. If an argument is given, it will be treated as the path to a custom configuration file.'
