# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: mounts
description: Print the configured file mounts
documentation:
    command: '[AI] The `hugo config mounts` command is used in Hugo, a popular static site generator for creating blogs and websites. This command is responsible for setting up file system mount points between the source content and the output directory during the build process. It reads the configuration file (usually named `config.toml`) to identify the paths that need to be mounted and then makes those directories accessible in the output location, allowing Hugo to properly generate the site using the specified content.'
