# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: watch [SERVICE...]
description: Watch build context for service and rebuild/refresh containers when files are updated
flags:
    --no-up: Do not build & start services before watching
    --quiet: hide build output
documentation:
    command: '[AI] `docker-compose alpha watch` is a command used with Docker Compose files to monitor for changes in the YAML file and automatically rebuild or recreate any affected services without having to manually run `docker-compose build` or `docker-compose up`. The `alpha` tag indicates this is an experimental feature that may have breaking changes in future releases.'
    flag:
        no-up: |-
            [AI] The `docker-compose` command `alpha watch --no-up` is used to monitor changes in Docker Compose files without starting or updating the services. Here's a breakdown of each part:

            * `docker-compose`: It is a command-line tool for defining and managing multi-container Docker applications using YAML Compose files.
            * `alpha`: This option indicates that you are using an experimental feature. In this case, it's the "watch" mode.
            * `watch`: This feature allows Docker Compose to automatically rebuild and restart services when changes are detected in the Compose file.
            * `--no-up`: This option is used with the "up" command and tells Docker Compose not to start or update the running services when a change is detected, but only to display the new service configurations. So, by using `alpha watch --no-up`, you're just monitoring changes in your Compose file without affecting the currently running containers.
        quiet: |-
            [AI] `docker-compose` is a tool for defining and running multi-container Docker applications. The command `docker-compose alpha watch --quiet` is used to monitor changes in Compose files or services, but it does so with minimal output.

            Here's a breakdown of each part of the command:

            1. `docker-compose`: This invokes the Docker Compose command-line interface.
            2. `alpha`: This indicates that we're using an alpha (pre-release) version of the Compose feature called 'watch'. New features in the 'alpha' stage are not yet considered stable and might have some breaking changes.
            3. `watch`: This is a Compose feature for automatically rebuilding, restarting, and reapplying changes to your services when detected file changes.
            4. `--quiet`: This option tells Docker Compose to run with minimal output. It means that the command will not print messages for every change detected unless an error occurs or when a new container is started.
