# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: scale [SERVICE=REPLICAS...]
description: 'Scale services '
flags:
    --no-deps: Don't start linked services.
documentation:
    command: '[AI] `docker-compose scale` is a command used with Docker Compose files to change the number of replicas for one or more services. It modifies the replication configuration in the compose file, without altering other parts of the file. For example, you can use it to scale up or down a service based on your needs, such as `docker-compose scale web=3`. This command does not affect running containers; it only updates the desired number of replicas for each service in the Compose file. To apply the changes, run `docker-compose up -d` afterwards.'
    flag:
        no-deps: '[AI] `docker-compose scale --no-deps` is a command used with Docker Compose to change the number of replicas for one or more services without affecting the replica count of other, non-depended services in the same Compose file. The `--no-deps` flag disables the dependency propagation, meaning it only scales the specified services and keeps the replication of their dependents unchanged.'
