# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: stop [OPTIONS] [SERVICE...]
description: Stop services
flags:
    -t, --timeout=: Specify a shutdown timeout in seconds
documentation:
    command: '[AI] `docker-compose stop` is a command used to gracefully stop all containers defined in a `docker-compose.yml` file. It sends a SIGTERM signal by default, allowing the containers to finish any ongoing tasks and cleanly shut down. If containers do not stop within a specified time (default is 10 seconds), `docker-compose` will use a harder SIGKILL signal to forcefully terminate them.'
    flag:
        timeout: '[AI] `docker-compose stop` is a command used to gracefully stop Docker services defined in a `docker-compose.yml` file. The `--timeout` option sets the maximum amount of time (in seconds) to wait for each container to stop before using the force (SIGKILL) signal. If a container fails to stop within the specified timeout, it will be forcibly terminated. Without `--timeout`, Docker Compose would use its default timeout value of 30 seconds.'
