# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Manage config options
flags:
    -h, --help: Print help (see more with '--help')
documentation:
    command: '[AI] `jj` is a popular JavaScript and TypeScript linting, formatting, and autocompletion tool. The `jj config` command is used to configure `jj` settings in a project. It reads or writes the `.jjrc` file (short for "Just-JavaScript Configuration File") that contains customization options for the `jj` tool. For instance, you can set up custom rules, linters, or formatters for your codebase by editing this file.'
    flag:
        help: '[AI] `jj config --help` is a command used in Jira CLI (Command Line Interface) tools like Jira CLI or JFrog CLI. It is not a specific flag itself but a request for help or documentation about the "config" sub-command. When executed, it displays detailed information about what the "config" command does and how to use it with various options and arguments. This can help users understand how to configure their Jira environments or other related settings using these CLI tools.'
