# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get [OPTIONS] <NAME>
aliases:
    - g
description: Get the value of a given config option.
flags:
    -h, --help: Print help (see more with '--help')
documentation:
    command: '[AI] The `jj config get` command is used within Jira Software''s Jenkins integration (known as JJ-CI) to retrieve the current configuration settings for a specific project or connection. It helps administrators and developers to view the current values of various configurations, such as Jira project keys, branch names, or build triggers, which are essential when troubleshooting issues or making modifications.'
    flag:
        help: '[AI] The `jj` command with the `config get --help` argument is used in the Jupyter Notebook environment or the Jupyterlab IDE to retrieve help information about the `config get` subcommand of the Jupyter JavaScript Core (jj) library. This command allows users to fetch the value of a specific configuration option from their Jupyter notebook server or client side settings. The `--help` flag displays detailed information on how to use this command, including its syntax, available options, and usage examples.'
