# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: help
description: Print this message or the help of the given subcommand(s)
documentation:
    command: '[AI] `jj config help` is a command used in Jira, specifically with Jira''s Jenkins integration plugin (JJ-CI), to display available configuration options and their descriptions for various settings related to the plugin. It helps users understand what each option does, providing essential information to effectively configure the plugin according to their project requirements.'
