# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config-schema
description: Print the JSON schema for the jj TOML config format
flags:
    -h, --help: Print help (see more with '--help')
documentation:
    command: '[AI] The `jj util config-schema` command is a Jupyter Notebook utility used to generate or update the schema file for JSON notebooks. This file defines the structure and types of keys in the metadata section of the notebook, allowing tools like Jupyter Notebook Viewer and nbformat to properly interpret and render the notebook. The schema file is saved as a `.json` file named `notebook.json` in the root directory of the notebook.'
    flag:
        help: |-
            [AI] The command `jj util config-schema --help` is used with Jira JIRA Software's CLI (Command Line Interface) tool, specifically with its utility named `jj util`. This command is used to display the help and usage information for the `config-schema` sub-command.

            The purpose of `config-schema` is to generate a JSON schema file from an existing Jira configuration, making it easier to understand the structure and format of the configuration data. By adding the `--help` flag, you'll receive detailed information about how to use this command correctly, including any available options or arguments, examples, and usage scenarios.

            In summary, this command helps you generate a JSON schema from your Jira configuration while providing contextual help to guide you through the process.
