# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: search
description: Search for a New Relic application
flags:
    -n, --name=: search for results matching the given APM application name
documentation:
    command: '[AI] `newrelic apm application search` is a command used in New Relic APM (Application Performance Monitoring) to query and filter applications monitored by New Relic. This command helps users quickly locate specific applications based on their names or other attributes like environment, status, or performance scores. The result set will display relevant application details such as the name, environment, and status. It''s an essential tool for managing and monitoring applications in a large-scale environment with multiple New Relic APM applications.'
    flag:
        name: '[AI] The `newrelic apm application search --name` command is used in New Relic APM (Application Performance Monitoring) to search for applications by name within the New Relic platform. This command returns a list of applications that match the specified name query, enabling users to easily identify and manage their applications.'
