# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: Configuration utilities/helpers for New Relic agents
documentation:
    command: '[AI] The `newrelic-agent config` command is used to configure New Relic''s agent, which is a software component that monitors and reports on the performance of applications and infrastructure. It allows you to modify various settings related to data collection, application identification, and integration with other systems. You can use this command to update specific configurations or apply new ones, ensuring your agent is tailored to your unique environment.'
