# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: reset
aliases:
    - rm
    - delete
description: Reset a configuration value to its default
flags:
    -k, --key=: the key to delete
documentation:
    command: '[AI] The `newrelic config reset` command is used to restore the New Relic agent configuration to its default settings. This command is typically executed when you want to start fresh with the configuration, or if there have been issues that require a reset. Running this command will erase any customized settings you may have previously configured and revert them back to their out-of-the-box values.'
    flag:
        key: '[AI] The `newrelic config reset --key` command is used to reset a specific configuration key in New Relic, a software analytics company''s tool. This command resets the specified configuration key to its default value. By providing the key as an argument, you can target specific configurations without affecting others. It''s essential for correcting misconfigurations or when starting with a fresh setup.'
