# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: list
aliases:
    - ls
description: List the current configuration values
documentation:
    command: '[AI] The `newrelic config list` command is used in New Relic''s CLI (Command Line Interface) tools to display a list of configured applications and their corresponding configurations. This includes details like application ID, name, environment, and API key. It helps users manage multiple applications within the New Relic platform easily.'
