# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get
description: Get a configuration value
flags:
    -k, --key=: the key to get
documentation:
    command: '[AI] The `newrelic config get` command is used in New Relic''s CLI (Command Line Interface) to retrieve specific configuration settings from an application or infrastructure being monitored by New Relic. This command allows users to view the current configuration of their New Relic accounts, applications, and other associated resources directly from the terminal. It helps in troubleshooting issues, comparing configurations between different environments, and maintaining accurate records of configuration settings.'
    flag:
        key: '[AI] The `newrelic config get` is a command used in New Relic''s CLI (Command Line Interface) tool to retrieve configuration settings. The `--key` option is used to specify the name or key of the particular configuration setting that you want to retrieve. For example, `newrelic config get --key appname` would return the value set for the application name in your New Relic account.'
