# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: application
description: Interact with New Relic APM applications
persistentflags:
    -g, --guid=: search for results matching the given APM application GUID
documentation:
    command: '[AI] "newrelic apm application" is a command used in New Relic''s Application Performance Monitoring (APM) tool. It creates or manages an application definition within New Relic APM. This command can be used to install the New Relic agent on a new application, configure settings, and start monitoring application performance in real-time. It helps developers and operations teams gain insights into their application''s health, identify bottlenecks, and optimize performance.'
