# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: get
description: Get a New Relic application
documentation:
    command: '[AI] The `newrelic apm application get` is a command used in New Relic''s command-line interface (CLI) tool for retrieving details about a specific New Relic Application Performance Monitoring (APM) application. This command helps you to fetch the configuration and status of your application monitored by New Relic, including its name, ID, environment, and other relevant information. You can use this command along with filters like application ID or name to get detailed data for a specific application.'
